"""consema.protocol — the language-neutral protocol surface.

Exports the contract registry (v1-v7, 16/18/25/25/30/38/41 records), the
error-code registry (v1-v7, 55/62/90/92/132/166/187 codes), the canonical
tagged JSON transport `core.portable-value-json@1`, the PVCE transport
under protocol limits, the `core.diagnostic@1` record, the registry
descriptors (profile/capability/manifest), query definition validation,
the CLI machine records (core.cli-output@1, core.batch-plan@1,
core.batch-result@1), the `core.protocol-message@1` envelope, and the CLI
exit classification.

Authority: RFC 0015/0016; crates/consema-protocol (registry arbitration and
byte behavior); conformance/vectors (protocol-v1.json, protocol-v2.json,
cli-v1.json); go/protocol as a cross-reference only.
"""

from consema.protocol.canonical import (
    PortableValueJSONSchema,
    decode_json,
    decode_pvce,
    encode_json,
    encode_pvce,
)
from consema.protocol.cli import (
    BatchPlanFileEntry,
    BatchPlanFileStatus,
    BatchPlanMessage,
    BatchResultFileEntry,
    BatchResultFileStatus,
    BatchResultMessage,
    CliCommand,
    CliOutputMessage,
    ContentDigest,
    EditOperationSummary,
    EncodingFacts,
    FormatOperationId,
    Redaction,
    SourceEncoding,
    SourcePatch,
    SourceReplacement,
    payload_schemas,
    parse_cli_command,
    windows_code_page_from_number,
)
from consema.protocol.contract import (
    ContractId,
    ContractRegistry,
    ContractStability,
    ProtocolMessage,
    validate_identifier,
    validate_namespace,
)
from consema.protocol.diagnostic import (
    Diagnostic,
    FixApplicability,
    FixProposal,
    RelatedSourceLocation,
    Severity,
    SourceLocation,
    parse_fix_applicability,
    parse_severity,
    validate_diagnostic_code,
)
from consema.protocol.envelope import validate_registered_payload
from consema.protocol.error_registry import (
    DiagnosticCategory,
    ErrorCodeDescriptor,
    ErrorCodeRegistry,
    error_code_manifest_value,
    validate_error_code_manifest_value,
    validate_versioned_code,
)
from consema.protocol.errors import ProtocolError, ProtocolErrorKind, invalid, resource
from consema.protocol.exit_class import (
    ExitClass,
    classify,
    classify_error_code,
    exit_code,
    parse_exit_class,
)
from consema.protocol.limits import ProtocolLimits
from consema.protocol.query import (
    ExecutableQuery,
    ExpressionKind,
    MatchRole,
    OperatorCall,
    QueryDefinition,
    QueryDefinitionCodec,
    QueryDomain,
    QueryExpression,
    QueryFailure,
    QueryFailureKind,
    QuerySelection,
    ValidatedQuery,
    domain_hcl_lossless_syntax_v1,
    domain_hcl_native_v1,
    domain_ini_lossless_syntax_v1,
    domain_ini_native_v1,
    domain_java_properties_lossless_syntax_v1,
    domain_java_properties_native_v1,
    domain_json_lossless_syntax_v1,
    domain_json_lossless_syntax_v2,
    domain_json_native_v1,
    domain_json_native_v2,
    domain_plist_binary_structure_v1,
    domain_plist_lossless_syntax_v1,
    domain_plist_native_v1,
    domain_portable_graph_v1,
    domain_portable_value_v1,
    domain_toml_lossless_syntax_v1,
    domain_toml_native_v1,
    domain_xml_lossless_syntax_v1,
    domain_xml_native_v1,
    domain_yaml_lossless_syntax_v1,
    domain_yaml_native_v1,
)
from consema.protocol.registry_descriptor import (
    CapabilityDeclaration,
    CapabilityId,
    CapabilitySet,
    ContractManifestEntry,
    ErrorCodeManifestEntry,
    ImplementationSupport,
    Precondition,
    ProfileDescriptor,
    ProfileReference,
    RegistryManifest,
    SupportKind,
    VerificationStatus,
)

__all__ = [
    "BatchPlanFileEntry",
    "BatchPlanFileStatus",
    "BatchPlanMessage",
    "BatchResultFileEntry",
    "BatchResultFileStatus",
    "BatchResultMessage",
    "CapabilityDeclaration",
    "CapabilityId",
    "CapabilitySet",
    "CliCommand",
    "CliOutputMessage",
    "ContentDigest",
    "ContractId",
    "ContractManifestEntry",
    "ContractRegistry",
    "ContractStability",
    "Diagnostic",
    "DiagnosticCategory",
    "EditOperationSummary",
    "EncodingFacts",
    "ErrorCodeDescriptor",
    "ErrorCodeManifestEntry",
    "ErrorCodeRegistry",
    "ExecutableQuery",
    "ExitClass",
    "ExpressionKind",
    "FixApplicability",
    "FixProposal",
    "FormatOperationId",
    "ImplementationSupport",
    "MatchRole",
    "OperatorCall",
    "PortableValueJSONSchema",
    "Precondition",
    "ProfileDescriptor",
    "ProfileReference",
    "ProtocolError",
    "ProtocolErrorKind",
    "ProtocolLimits",
    "ProtocolMessage",
    "QueryDefinition",
    "QueryDefinitionCodec",
    "QueryDomain",
    "QueryExpression",
    "QueryFailure",
    "QueryFailureKind",
    "QuerySelection",
    "Redaction",
    "RegistryManifest",
    "RelatedSourceLocation",
    "Severity",
    "SourceEncoding",
    "SourceLocation",
    "SourcePatch",
    "SourceReplacement",
    "SupportKind",
    "ValidatedQuery",
    "VerificationStatus",
    "classify",
    "classify_error_code",
    "decode_json",
    "decode_pvce",
    "domain_hcl_lossless_syntax_v1",
    "domain_hcl_native_v1",
    "domain_ini_lossless_syntax_v1",
    "domain_ini_native_v1",
    "domain_java_properties_lossless_syntax_v1",
    "domain_java_properties_native_v1",
    "domain_json_lossless_syntax_v1",
    "domain_json_lossless_syntax_v2",
    "domain_json_native_v1",
    "domain_json_native_v2",
    "domain_plist_binary_structure_v1",
    "domain_plist_lossless_syntax_v1",
    "domain_plist_native_v1",
    "domain_portable_graph_v1",
    "domain_portable_value_v1",
    "domain_toml_lossless_syntax_v1",
    "domain_toml_native_v1",
    "domain_xml_lossless_syntax_v1",
    "domain_xml_native_v1",
    "domain_yaml_lossless_syntax_v1",
    "domain_yaml_native_v1",
    "encode_json",
    "encode_pvce",
    "error_code_manifest_value",
    "exit_code",
    "invalid",
    "parse_cli_command",
    "parse_exit_class",
    "parse_fix_applicability",
    "parse_severity",
    "payload_schemas",
    "resource",
    "validate_diagnostic_code",
    "validate_error_code_manifest_value",
    "validate_identifier",
    "validate_namespace",
    "validate_registered_payload",
    "validate_versioned_code",
    "windows_code_page_from_number",
]
