"""Canonical ``plist.xml-canonical@1`` / ``plist.binary-canonical@1``
materialization (RFC 0013 §10).

Authority (Rust arbitration for exact bytes and semantics):

- Record contract and request contract: crates/consema-plist/src/
  materialization.rs:1-115 — the input is the exact ``plist.value-tree@1``
  record (``{ "record": "plist.value-tree@1", "root": <value>,
  "truncate_policy": "TruncateWithReport" | absent }``); dict associations
  are ordered and duplicate keys are preserved; ``plist.xml-canonical@1``
  requires UTF-8 + Lf, ``plist.binary-canonical@1`` requires Binary + None.
- XML writer: materialization.rs:1105-1209 (Apple header spelling,
  four-space indentation, LF line endings, a trailing newline; the root
  value element at depth 1; ``<key>`` lines before every value; data
  base64 wrapped at ``76 - 8 * depth`` against the indented budget
  (encode_base64_wrapped 1338-1369); whole-second dates with the explicit
  TruncateWithReport policy (RFC 0013 §10.1); escape_xml_text 1218-1234).
- Binary writer: materialization.rs:1414-1520 (document-ordered object
  table: the root is object 0, every dictionary is followed by its key
  objects and then its values; minimal integer widths with negatives
  always 8 bytes; Float32 width facts preserved; identical deduplicable
  scalars share one object at first occurrence; minimal UID widths; the
  offset/ref sizes are the minimal widths satisfying the trailer
  sufficiency checks; ``sortVersion = 0x00``; write_sized 1549-1559).
- Closure: materialization.rs:60-66, 489-535 — every style validates the
  complete input, encodes, reparses the exact generated bytes under the
  promised Profile, and compares the reparsed native model to the promised
  input semantics; failure returns no target Document, partial bytes, or
  partial provenance (RFC 0013 §10.3).
- Failure mapping: materialization.rs:78-95 and go/plist/materialization.go
  Code() — a Date kind marks a value-tree date leaf the XML whole-second
  calendar cannot express (``plist.materialization.fractional-date@1``);
  the returned failure carries the plist-owned ``plist.materialization.*@1``
  spellings for the plist facts (fractional-date, unrepresentable,
  resource-limit; RFC 0013 §12) and the shared ``core.materialization.*@1``
  codes for the request/formation failures.

This module defines a plist-owned ``PlistMaterializationFailure`` that
carries the stable ``plist.materialization.*@1`` code for the fractional-
date case and delegates the shared codes to consema.document's
``MaterializationFailure``; ``materialize`` surfaces every plist failure
through ``_PlistCodedFailure`` so the plist spellings reach the caller
directly.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass

from consema.core.value import Decimal, Kind, PortableValue
from consema.document.materialization import (
    CompleteMaterialization,
    FailedMaterializationAttempt,
    MaterializationFailure,
    MaterializationFailureKind,
    MaterializationFidelity,
    MaterializationLimits,
    MaterializationProvenanceEntry,
    MaterializationProvenanceMap,
    MaterializationRelation,
    MaterializationReport,
    MaterializationRequest,
    MaterializationResult,
    MaterializedOrigin,
    NewlinePolicy,
)
from consema.document.structural import FormationStatus, NodeRole
from consema.plist.conversion import _f64_bits as _bits_of
from consema.plist.document import PlistDocument, PlistRepresentation
from consema.plist.kinds import (
    PlistEncodingSelection,
    PlistParseLimits,
    PlistProfile,
    RealWidth,
)
from consema.plist.native import (
    PLIST_EPOCH_OFFSET_UNIX,
    PlistArray,
    PlistBoolean,
    PlistData,
    PlistDate,
    PlistDict,
    PlistDictEntry,
    PlistDocument as NativeDocument,
    PlistDocumentBuilder,
    PlistInteger,
    PlistKey,
    PlistReal,
    PlistString,
    PlistUid,
    PlistValue,
    PlistValueRef,
)
from consema.plist.parser_xml import parse_xml

_STYLE_XML = "plist.xml-canonical"
_STYLE_BINARY = "plist.binary-canonical"
_VALUE_TREE_RECORD = "plist.value-tree@1"
_TRUNCATE_POLICY = "TruncateWithReport"
_PLIST_EPOCH_SPELLING = "2001-01-01T00:00:00Z"
_FRACTIONAL_DATE_CODE = "plist.materialization.fractional-date@1"
_NEGATIVE_ZERO_BITS = 0x8000_0000_0000_0000
_EXACT_UNIX_SECONDS_BOUND = 9_007_199_254_740_992.0


class _Style(enum.Enum):
    XML = "xml"
    BINARY = "binary"


# ---------------------------------------------------------------------------
# Plist-owned failure surface
# ---------------------------------------------------------------------------


class PlistMaterializationFailureKind(enum.Enum):
    """Stable plist materialization failure categories (materialization.rs:
    78-95 plus the shared core kinds)."""

    FRACTIONAL_DATE = "fractional-date"
    UNREPRESENTABLE = "unrepresentable"
    RESOURCE_LIMIT = "resource-limit"
    INVALID_REQUEST = "invalid-request"
    UNSUPPORTED_PROFILE = "unsupported-profile"
    UNSUPPORTED_STYLE = "unsupported-style"
    UNSUPPORTED_ENCODING = "unsupported-encoding"
    UNSUPPORTED_NEWLINE = "unsupported-newline"
    FORMATION_FAILED = "formation-failed"


class _PlistCodedFailure(MaterializationFailure):
    """Shared-shaped failure carrying the plist-owned ``plist.materialization.*@1``
    spellings for the plist materialization facts (RFC 0013 §12).

    Mirrors go/plist/materialization.go Code() (lines 125-140): a Date-kind
    Unrepresentable maps to ``plist.materialization.fractional-date@1``,
    every other plist Unrepresentable to ``plist.materialization.unrepresentable@1``,
    and ResourceLimit to ``plist.materialization.resource-limit@1``; the
    shared request/formation failures keep the shared
    ``core.materialization.*@1`` codes.
    """

    @property
    def code(self) -> str:
        if self.kind is MaterializationFailureKind.UNREPRESENTABLE:
            if self.name == "date":
                return "plist.materialization.fractional-date@1"
            return "plist.materialization.unrepresentable@1"
        if self.kind is MaterializationFailureKind.RESOURCE_LIMIT:
            return "plist.materialization.resource-limit@1"
        return super().code


class PlistMaterializationFailure(Exception):
    """Stable plist materialization failure.

    Code mapping authority: materialization.rs:78-95 and
    crates/consema-conformance/src/plist_v1.rs:1800-1816 — a Date kind maps
    to ``plist.materialization.fractional-date@1``, other plist facts to
    ``plist.materialization.unrepresentable@1`` / ``resource-limit@1``, and
    the shared request/formation failures to the ``core.materialization.*@1``
    codes.
    """

    def __init__(
        self,
        kind: PlistMaterializationFailureKind,
        *,
        name: str | None = None,
        detail: str | None = None,
    ) -> None:
        super().__init__(kind.value)
        self.kind = kind
        self.name = name
        self.detail = detail

    @property
    def code(self) -> str:
        if self.kind is PlistMaterializationFailureKind.FRACTIONAL_DATE:
            return _FRACTIONAL_DATE_CODE
        if self.kind is PlistMaterializationFailureKind.UNREPRESENTABLE:
            return "plist.materialization.unrepresentable@1"
        if self.kind is PlistMaterializationFailureKind.RESOURCE_LIMIT:
            return "plist.materialization.resource-limit@1"
        return {
            PlistMaterializationFailureKind.INVALID_REQUEST: "core.materialization.invalid-request@1",
            PlistMaterializationFailureKind.UNSUPPORTED_PROFILE: "core.materialization.unsupported-profile@1",
            PlistMaterializationFailureKind.UNSUPPORTED_STYLE: "core.materialization.unsupported-style@1",
            PlistMaterializationFailureKind.UNSUPPORTED_ENCODING: "core.materialization.unsupported-encoding@1",
            PlistMaterializationFailureKind.UNSUPPORTED_NEWLINE: "core.materialization.unsupported-newline@1",
            PlistMaterializationFailureKind.FORMATION_FAILED: "core.materialization.formation-failed@1",
        }[self.kind]


# ---------------------------------------------------------------------------
# Input record parsing
# ---------------------------------------------------------------------------


class _ValueKind(enum.Enum):
    DICT = "dict"
    ARRAY = "array"
    STRING = "string"
    INTEGER = "integer"
    REAL = "real"
    BOOLEAN = "boolean"
    DATE = "date"
    DATA = "data"
    UID = "uid"


@dataclass(slots=True)
class _ValueNode:
    kind: _ValueKind
    path: tuple
    entries: list = None  # type: ignore[assignment]  # (key: PlistString, value: _ValueNode)
    elements: list = None  # type: ignore[assignment]
    string: PlistString | None = None
    integer: int | None = None
    real: PlistReal | None = None
    boolean: bool | None = None
    date_seconds: float | None = None
    data: bytes | None = None
    uid: int | None = None

    def __post_init__(self) -> None:
        if self.entries is None:
            self.entries = []
        if self.elements is None:
            self.elements = []


def _decimal_to_f64(decimal: Decimal) -> float | None:
    """Converts one canonical Decimal to its double value
    (materialization.rs:665-668)."""
    try:
        return float(decimal.coefficient) * (10.0 ** decimal.exponent)
    except (OverflowError, ValueError):
        return None


def _leaf_real(value: PortableValue) -> PlistReal | None:
    """One real leaf from the BinaryFloat64 / BinaryFloat32 / Decimal
    spellings (materialization.rs:35-45)."""
    kind = value.kind
    if kind is Kind.BINARY_FLOAT64:
        import struct

        bits = value.as_binary_float64()
        return PlistReal.from_bits(RealWidth.FLOAT64, bits)
    if kind is Kind.BINARY_FLOAT32:
        return PlistReal.from_bits(RealWidth.FLOAT32, value.as_binary_float32())
    if kind is Kind.DECIMAL:
        converted = _decimal_to_f64(value.as_decimal())
        if converted is None:
            return None
        return PlistReal.double(converted)
    return None


def _leaf_seconds(value: PortableValue) -> float | None:
    """One date leaf's exact double seconds from the ``{epoch, seconds}``
    spelling (materialization.rs:32-34)."""
    entries = value.as_object()
    fields = dict(entries)
    epoch = fields.get("epoch")
    seconds = fields.get("seconds")
    if epoch is None or seconds is None:
        return None
    if epoch.kind is not Kind.STRING or epoch.as_string() != _PLIST_EPOCH_SPELLING:
        return None
    if seconds.kind is Kind.BINARY_FLOAT64:
        import struct

        return struct.unpack(">d", struct.pack(">Q", seconds.as_binary_float64()))[0]
    if seconds.kind is Kind.DECIMAL:
        return _decimal_to_f64(seconds.as_decimal())
    return None


def _leaf_hex(value: PortableValue) -> bytes | None:
    """One data leaf from the ``{hex: String}`` spelling; strict lowercase
    or uppercase hex (materialization.rs:36-37)."""
    entries = value.as_object()
    fields = dict(entries)
    hex_value = fields.get("hex")
    if hex_value is None or hex_value.kind is not Kind.STRING:
        return None
    text = hex_value.as_string()
    if len(text) % 2 != 0:
        return None
    try:
        return bytes.fromhex(text)
    except ValueError:
        return None


def _leaf_uid(value: PortableValue) -> int | None:
    entries = value.as_object()
    fields = dict(entries)
    uid = fields.get("uid")
    if uid is None or uid.kind is not Kind.INTEGER:
        return None
    integer = uid.as_integer()
    if not 0 <= integer <= 0xFFFF_FFFF:
        return None
    return integer


def parse_record(value: PortableValue, analyzed: list, depth: int = 0) -> _ValueNode:
    """Parses one ``plist.value-tree@1`` record into the value-node shape
    (materialization.rs:180-660). Every admission gate fails atomically."""
    if depth > 256:
        raise PlistMaterializationFailure(
            PlistMaterializationFailureKind.RESOURCE_LIMIT, name="depth"
        )
    analyzed.append(("root",))
    if value.kind is not Kind.OBJECT:
        raise PlistMaterializationFailure(
            PlistMaterializationFailureKind.INVALID_REQUEST,
            detail="record must be an object",
        )
    fields = dict(value.as_object())
    record = fields.get("record")
    root = fields.get("root")
    if record is None or record.kind is not Kind.STRING or record.as_string() != _VALUE_TREE_RECORD:
        raise PlistMaterializationFailure(
            PlistMaterializationFailureKind.INVALID_REQUEST,
            detail="record identity",
        )
    if root is None:
        raise PlistMaterializationFailure(
            PlistMaterializationFailureKind.INVALID_REQUEST,
            detail="missing root",
        )
    truncate = fields.get("truncate_policy")
    policy = None
    if truncate is not None:
        if truncate.kind is not Kind.STRING or truncate.as_string() != _TRUNCATE_POLICY:
            raise PlistMaterializationFailure(
                PlistMaterializationFailureKind.INVALID_REQUEST,
                detail="truncate policy",
            )
        policy = _TRUNCATE_POLICY
    return _parse_value(root, ("root",), policy, analyzed, depth + 1)


def _parse_value(
    value: PortableValue, path: tuple, truncate: str | None, analyzed: list, depth: int
) -> _ValueNode:
    analyzed.append(path)
    kind = value.kind
    if kind is Kind.ENTRY_MAPPING:
        node = _ValueNode(_ValueKind.DICT, path)
        for position, (key_value, entry_value) in enumerate(value.as_entry_mapping()):
            if key_value.kind is not Kind.STRING:
                raise PlistMaterializationFailure(
                    PlistMaterializationFailureKind.UNREPRESENTABLE,
                    detail="non-string dict key",
                )
            key = PlistString.from_unicode(key_value.as_string())
            child = _parse_value(
                entry_value, path + (position,), truncate, analyzed, depth + 1
            )
            node.entries.append((key, child))
        return node
    if kind is Kind.OBJECT:
        entries = value.as_object()
        fields = dict(entries)
        # An Object whose members are exactly `epoch` + `seconds`, `uid`,
        # or `hex` is the corresponding typed leaf; any other Object is a
        # dictionary (materialization.rs:47-53).
        if set(fields) == {"epoch", "seconds"}:
            seconds = _leaf_seconds(value)
            if seconds is None:
                raise PlistMaterializationFailure(
                    PlistMaterializationFailureKind.UNREPRESENTABLE,
                    detail="date",
                )
            return _ValueNode(_ValueKind.DATE, path, date_seconds=seconds)
        if set(fields) == {"hex"}:
            data = _leaf_hex(value)
            if data is None:
                raise PlistMaterializationFailure(
                    PlistMaterializationFailureKind.UNREPRESENTABLE,
                    detail="data",
                )
            return _ValueNode(_ValueKind.DATA, path, data=data)
        if set(fields) == {"uid"}:
            uid = _leaf_uid(value)
            if uid is None:
                raise PlistMaterializationFailure(
                    PlistMaterializationFailureKind.UNREPRESENTABLE,
                    detail="uid",
                )
            return _ValueNode(_ValueKind.UID, path, uid=uid)
        node = _ValueNode(_ValueKind.DICT, path)
        for position, (name, entry_value) in enumerate(entries):
            child = _parse_value(
                entry_value, path + (position,), truncate, analyzed, depth + 1
            )
            node.entries.append((PlistString.from_unicode(name), child))
        return node
    if kind is Kind.SEQUENCE:
        node = _ValueNode(_ValueKind.ARRAY, path)
        for position, element in enumerate(value.as_sequence()):
            node.elements.append(
                _parse_value(element, path + (position,), truncate, analyzed, depth + 1)
            )
        return node
    if kind is Kind.STRING:
        return _ValueNode(_ValueKind.STRING, path, string=PlistString.from_unicode(value.as_string()))
    if kind is Kind.INTEGER:
        integer = value.as_integer()
        if not -(1 << 63) <= integer <= (1 << 63) - 1:
            raise PlistMaterializationFailure(
                PlistMaterializationFailureKind.UNREPRESENTABLE,
                detail="integer range",
            )
        return _ValueNode(_ValueKind.INTEGER, path, integer=integer)
    if kind in (Kind.BINARY_FLOAT64, Kind.BINARY_FLOAT32, Kind.DECIMAL):
        real = _leaf_real(value)
        if real is None:
            raise PlistMaterializationFailure(
                PlistMaterializationFailureKind.UNREPRESENTABLE,
                detail="real",
            )
        return _ValueNode(_ValueKind.REAL, path, real=real)
    if kind is Kind.BOOLEAN:
        return _ValueNode(_ValueKind.BOOLEAN, path, boolean=value.as_boolean())
    if kind is Kind.BYTES:
        return _ValueNode(_ValueKind.DATA, path, data=value.as_bytes())
    raise PlistMaterializationFailure(
        PlistMaterializationFailureKind.UNREPRESENTABLE,
        detail=kind.value,
    )


# ---------------------------------------------------------------------------
# XML writer (materialization.rs:1105-1209)
# ---------------------------------------------------------------------------


def _write_indent(out: list[str], depth: int) -> None:
    for _ in range(depth):
        out.append("    ")


def _escape_xml_text(text: str) -> str:
    """Escapes XML text content (RFC 0013 §4.9, §10.1): ``&``, ``<``, ``>``,
    and a literal CR (materialization.rs:1218-1234)."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\r", "&#13;")
    )


def _render_real(real: PlistReal) -> str:
    """Deterministic shortest-round-trip decimal spelling of one real
    (RFC 0013 §4.6, §10.1; materialization.rs:1235-1253)."""
    value = real.as_f64()
    if value != value:
        return "nan"
    if abs(value) == float("inf"):
        return "-inf" if value < 0 else "inf"
    return repr(value)


def _civil_from_days(days: int) -> tuple[int, int, int]:
    z = days + 719_468
    era = (z if z >= 0 else z - 146_096) // 146_097
    day_of_era = z - era * 146_097
    year_of_era = (
        day_of_era - day_of_era // 1_460 + day_of_era // 36_524 - day_of_era // 146_096
    ) // 365
    year = year_of_era + era * 400
    day_of_year = day_of_era - (365 * year_of_era + year_of_era // 4 - year_of_era // 100)
    month_prime = (5 * day_of_year + 2) // 153
    day = day_of_year - (153 * month_prime + 2) // 5 + 1
    month = month_prime + (3 if month_prime < 10 else -9)
    year = year + 1 if month <= 2 else year
    return (year, month, day)


def _whole_second_date(seconds: float) -> tuple[int, int, int, int, int, int] | None:
    """Decomposes exact plist-epoch seconds into XML calendar fields
    (materialization.rs:1292-1336)."""
    if seconds != int(seconds):
        return None
    unix = seconds + PLIST_EPOCH_OFFSET_UNIX
    if abs(unix) >= _EXACT_UNIX_SECONDS_BOUND:
        return None
    unix_int = int(unix)
    days = unix_int // 86_400
    seconds_of_day = unix_int % 86_400
    year, month, day = _civil_from_days(days)
    if abs(year) > 0xFFFFFFFF:
        return None
    hour = seconds_of_day // 3_600
    minute = (seconds_of_day % 3_600) // 60
    second = seconds_of_day % 60
    return (year, month, day, hour, minute, second)


def _render_date(year: int, month: int, day: int, hour: int, minute: int, second: int) -> str:
    sign = "-" if year < 0 else ""
    return f"{sign}{abs(year):04}-{month:02}-{day:02}T{hour:02}:{minute:02}:{second:02}Z"


def _encode_base64_wrapped(bytes_: bytes, depth: int) -> str:
    """Standard-alphabet base64 wrapped at ``76 - 8 * depth`` with the
    indentation counted against the budget (RFC 0013 §4.8, §10.1;
    materialization.rs:1338-1369)."""
    import base64

    budget = max(76 - 8 * depth, 1)
    encoded = base64.b64encode(bytes_).decode("ascii")
    out: list[str] = []
    line = 0
    for character in encoded:
        if line + 1 > budget and line > 0:
            out.append("\n")
            _write_indent(out, depth)
            line = 0
        out.append(character)
        line += 1
    return "".join(out)


def _serialize_xml(
    root: _ValueNode,
    truncate: str | None,
    limits: MaterializationLimits,
    report: list,
) -> tuple[bytes, list]:
    out: list[str] = []
    out.append('<?xml version="1.0" encoding="UTF-8"?>\n')
    out.append(
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
    )
    out.append('<plist version="1.0">\n')
    items: list = []
    rank = 0
    _emit_value_xml(out, root, 1, items, rank, truncate, limits, report)
    out.append("</plist>\n")
    text = "".join(out)
    if len(text.encode("utf-8")) > limits.max_output_bytes:
        raise PlistMaterializationFailure(
            PlistMaterializationFailureKind.RESOURCE_LIMIT, name="output-bytes"
        )
    return text.encode("utf-8"), items


def _emit_value_xml(
    out: list[str],
    node: _ValueNode,
    depth: int,
    items: list,
    rank: int,
    truncate: str | None,
    limits: MaterializationLimits,
    report: list,
) -> int:
    """Emits one value element at the given depth; the node's target ordinal
    is its post-order rank (materialization.rs:1123-1209)."""
    kind = node.kind
    if kind is _ValueKind.DICT:
        _write_indent(out, depth)
        if not node.entries:
            out.append("<dict></dict>\n")
        else:
            out.append("<dict>\n")
            for key, child in node.entries:
                _write_indent(out, depth + 1)
                out.append("<key>")
                out.append(_escape_xml_text(key.to_unicode()))
                out.append("</key>\n")
                rank = _emit_value_xml(out, child, depth + 1, items, rank, truncate, limits, report)
            _write_indent(out, depth)
            out.append("</dict>\n")
    elif kind is _ValueKind.ARRAY:
        _write_indent(out, depth)
        if not node.elements:
            out.append("<array></array>\n")
        else:
            out.append("<array>\n")
            for element in node.elements:
                rank = _emit_value_xml(out, element, depth + 1, items, rank, truncate, limits, report)
            _write_indent(out, depth)
            out.append("</array>\n")
    elif kind is _ValueKind.STRING:
        _write_indent(out, depth)
        out.append("<string>")
        out.append(_escape_xml_text(node.string.to_unicode()))
        out.append("</string>\n")
    elif kind is _ValueKind.INTEGER:
        _write_indent(out, depth)
        out.append(f"<integer>{node.integer}</integer>\n")
    elif kind is _ValueKind.REAL:
        _write_indent(out, depth)
        out.append(f"<real>{_render_real(node.real)}</real>\n")
    elif kind is _ValueKind.BOOLEAN:
        _write_indent(out, depth)
        out.append("<true/>\n" if node.boolean else "<false/>\n")
    elif kind is _ValueKind.DATE:
        seconds = node.date_seconds
        fields = _whole_second_date(seconds)
        if fields is None:
            if truncate == _TRUNCATE_POLICY:
                fields = _whole_second_date(float(int(seconds)))
            if fields is None:
                raise PlistMaterializationFailure(
                    PlistMaterializationFailureKind.FRACTIONAL_DATE,
                    detail=f"seconds={seconds!r}",
                )
            # One report event per truncated date, with the input value
            # path and the original seconds (RFC 0013 §10.1, hard gate 3);
            # the promised semantics become the truncated seconds so the
            # reparse closure stays exact.
            report.append(
                (
                    _FRACTIONAL_DATE_CODE,
                    node.path,
                    seconds,
                )
            )
            if len(report) > limits.max_report_entries:
                raise PlistMaterializationFailure(
                    PlistMaterializationFailureKind.RESOURCE_LIMIT,
                    name="report-entries",
                )
            node.date_seconds = float(int(seconds))
        _write_indent(out, depth)
        out.append(f"<date>{_render_date(*fields)}</date>\n")
    elif kind is _ValueKind.DATA:
        _write_indent(out, depth)
        out.append("<data>")
        out.append(_encode_base64_wrapped(node.data, depth))
        out.append("</data>\n")
    else:  # UID is binary-only
        raise PlistMaterializationFailure(
            PlistMaterializationFailureKind.UNREPRESENTABLE,
            detail="uid-in-xml",
        )
    items.append((node.path, rank))
    rank += 1
    if len("".join(out).encode("utf-8")) > limits.max_output_bytes:
        raise PlistMaterializationFailure(
            PlistMaterializationFailureKind.RESOURCE_LIMIT, name="output-bytes"
        )
    return rank


# ---------------------------------------------------------------------------
# Binary writer (materialization.rs:1414-1617)
# ---------------------------------------------------------------------------


def _write_sized(out: bytearray, marker: int, count: int) -> None:
    """Writes one sized marker: counts below 0x0F fit the low nibble, while
    the nibble 0x0F itself is the extended-size sentinel (RFC 0013 §5.4;
    materialization.rs:1549-1559)."""
    if count < 0x0F:
        out.append(marker | count)
        return
    out.append(marker | 0x0F)
    width = _unsigned_width(count)
    out.append(0x10 | {1: 0, 2: 1, 4: 2, 8: 3}[width])
    out.extend(count.to_bytes(width, "big"))


def _write_string_object(out: bytearray, string: PlistString) -> None:
    """Writes one string object: the ASCII marker when every code unit is
    below 0x80, else the UTF-16BE marker (RFC 0013 §5.6;
    materialization.rs:1524-1541)."""
    units = string.code_units
    if all(unit < 0x80 for unit in units):
        _write_sized(out, 0x50, len(units))
        for unit in units:
            out.append(unit)
    else:
        _write_sized(out, 0x60, len(units))
        for unit in units:
            out.extend(unit.to_bytes(2, "big"))


def _write_be(out: bytearray, value: int, width: int) -> None:
    out.extend(value.to_bytes(width, "big"))


def _ref_size_for(max_index: int) -> int:
    size = 1
    capacity = 256
    while max_index >= capacity and size < 8:
        size += 1
        capacity *= 256
    return size


def _unsigned_width(value: int) -> int:
    if value <= 0xFF:
        return 1
    if value <= 0xFFFF:
        return 2
    if value <= 0xFFFF_FFFF:
        return 4
    return 8


def _integer_width(value: int) -> int:
    if value >= 0:
        return _unsigned_width(value)
    return 8


def _uid_width(value: int) -> int:
    if value <= 0xFF:
        return 1
    if value <= 0xFFFF:
        return 2
    if value <= 0xFF_FFFF:
        return 3
    return 4


class _ScalarKey:
    """Deduplication key of one scalar node (materialization.rs:1011-1081)."""

    __slots__ = ("kind", "payload")

    def __init__(self, kind: str, payload: object) -> None:
        self.kind = kind
        self.payload = payload

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, _ScalarKey):
            return NotImplemented
        return self.kind == other.kind and self.payload == other.payload

    def __hash__(self) -> int:
        return hash((self.kind, self.payload))


class _PlannedObject:
    __slots__ = ("kind", "keys", "values", "elements", "scalar")

    def __init__(self, kind: str) -> None:
        self.kind = kind  # "dict" | "array" | "scalar"
        self.keys: list[int] = []
        self.values: list[int] = []
        self.elements: list[int] = []
        self.scalar: _ScalarKey | None = None


def _plan_binary(root: _ValueNode, limits: MaterializationLimits) -> tuple[list[_PlannedObject], list, dict]:
    """Plans the document-ordered object table with scalar deduplication at
    first occurrence (materialization.rs:1011-1103)."""
    objects: list[_PlannedObject] = []
    items: list = []
    cache: dict[_ScalarKey, int] = {}

    def plan_node(node: _ValueNode) -> int:
        kind = node.kind
        if kind is _ValueKind.DICT:
            index = len(objects)
            objects.append(_PlannedObject("dict"))
            items.append((node.path, index))
            key_refs: list[int] = []
            for key, _ in node.entries:
                scalar = _ScalarKey("string", key.code_units)
                key_index = cache.get(scalar)
                if key_index is None:
                    key_index = len(objects)
                    objects.append(_PlannedObject("scalar"))
                    objects[-1].scalar = scalar
                    cache[scalar] = key_index
                key_refs.append(key_index)
            value_refs = [plan_node(entry_value) for _, entry_value in node.entries]
            objects[index].keys = key_refs
            objects[index].values = value_refs
            return index
        if kind is _ValueKind.ARRAY:
            index = len(objects)
            objects.append(_PlannedObject("array"))
            items.append((node.path, index))
            objects[index].elements = [plan_node(element) for element in node.elements]
            return index
        scalar = _node_scalar(node)
        if scalar is not None:
            cached = cache.get(scalar)
            if cached is not None:
                items.append((node.path, cached))
                return cached
            index = len(objects)
            objects.append(_PlannedObject("scalar"))
            objects[-1].scalar = scalar
            cache[scalar] = index
            items.append((node.path, index))
            return index
        raise PlistMaterializationFailure(
            PlistMaterializationFailureKind.UNREPRESENTABLE,
            detail=node.kind.value,
        )

    plan_node(root)
    return objects, items, cache


def _node_scalar(node: _ValueNode) -> _ScalarKey | None:
    kind = node.kind
    if kind is _ValueKind.STRING:
        return _ScalarKey("string", node.string.code_units)
    if kind is _ValueKind.INTEGER:
        return _ScalarKey("integer", node.integer)
    if kind is _ValueKind.REAL:
        return _ScalarKey("real", (node.real.width.value, node.real.bits))
    if kind is _ValueKind.BOOLEAN:
        return _ScalarKey("boolean", node.boolean)
    if kind is _ValueKind.DATE:
        return _ScalarKey("date", _bits_of(node.date_seconds))
    if kind is _ValueKind.DATA:
        return _ScalarKey("data", node.data)
    if kind is _ValueKind.UID:
        return _ScalarKey("uid", node.uid)
    return None


def _write_planned_object(
    out: bytearray, object_: _PlannedObject, ref_size: int
) -> None:
    """Writes one planned object: marker, size, payload, and references
    (RFC 0013 §5; materialization.rs:1456-1520)."""
    if object_.kind == "dict":
        count = len(object_.keys)
        _write_sized(out, 0xD0, count)
        for key in object_.keys:
            _write_be(out, key, ref_size)
        for value in object_.values:
            _write_be(out, value, ref_size)
    elif object_.kind == "array":
        count = len(object_.elements)
        _write_sized(out, 0xA0, count)
        for element in object_.elements:
            _write_be(out, element, ref_size)
    else:
        scalar = object_.scalar
        assert scalar is not None
        if scalar.kind == "string":
            _write_string_object(out, PlistString(scalar.payload))
        elif scalar.kind == "integer":
            value = scalar.payload
            width = _integer_width(value)
            out.append(0x10 | {1: 0, 2: 1, 4: 2, 8: 3}[width])
            _write_be(out, value & 0xFFFFFFFFFFFFFFFF, width)
        elif scalar.kind == "real":
            width_name, bits = scalar.payload
            if width_name == "Float64":
                out.append(0x23)
                _write_be(out, bits, 8)
            else:
                out.append(0x22)
                _write_be(out, bits, 4)
        elif scalar.kind == "boolean":
            out.append(0x09 if scalar.payload else 0x08)
        elif scalar.kind == "date":
            out.append(0x33)
            _write_be(out, scalar.payload, 8)
        elif scalar.kind == "data":
            _write_sized(out, 0x40, len(scalar.payload))
            out.extend(scalar.payload)
        elif scalar.kind == "uid":
            value = scalar.payload
            width = _uid_width(value)
            out.append(0x80 | (width - 1))
            _write_be(out, value, width)


def _serialize_binary(
    root: _ValueNode, limits: MaterializationLimits
) -> tuple[bytes, list]:
    """Serializes one record as a ``plist.binary@1`` source
    (materialization.rs:1414-1452)."""
    objects, items, _ = _plan_binary(root, limits)
    num_objects = len(objects)
    ref_size = _ref_size_for(num_objects)
    out = bytearray(b"bplist00")
    offsets: list[int] = []
    for object_ in objects:
        offsets.append(len(out))
        _write_planned_object(out, object_, ref_size)
        if len(out) > limits.max_output_bytes:
            raise PlistMaterializationFailure(
                PlistMaterializationFailureKind.RESOURCE_LIMIT, name="output-bytes"
            )
    offset_table_offset = len(out)
    offset_int_size = _ref_size_for(offset_table_offset)
    for offset in offsets:
        _write_be(out, offset, offset_int_size)
    out.extend(b"\x00\x00\x00\x00\x00")
    out.append(0)  # sortVersion
    out.append(offset_int_size)
    out.append(ref_size)
    out.extend(num_objects.to_bytes(8, "big"))
    out.extend((0).to_bytes(8, "big"))  # topObject: the root is object 0
    out.extend(offset_table_offset.to_bytes(8, "big"))
    return bytes(out), items


# ---------------------------------------------------------------------------
# Closure verification and provenance
# ---------------------------------------------------------------------------


def _reparse_limits(limits: MaterializationLimits, encoding_kind: str) -> PlistParseLimits:
    """Parse limits derived from the request so a bounded input cannot fail
    its own closure (materialization.rs:137-160)."""
    from consema.document.limits import ParseLimits

    return PlistParseLimits(
        common=ParseLimits(
            max_source_bytes=limits.max_output_bytes,
            max_nesting_depth=limits.max_depth,
            max_token_count=limits.max_output_bytes,
            max_node_count=limits.max_output_bytes,
            max_diagnostics=limits.max_report_entries,
        ),
        max_decoded_utf8_bytes=limits.max_output_bytes * 3,
        max_decoded_scalars=limits.max_output_bytes,
        max_object_count=limits.max_input_nodes,
        max_container_depth=limits.max_depth,
        max_dict_entries=limits.max_input_nodes,
        max_array_elements=limits.max_input_nodes,
        max_duplicate_key_group_members=limits.max_input_nodes,
        max_string_code_units=limits.max_output_bytes,
        max_data_bytes=limits.max_output_bytes,
        max_uid_count=limits.max_input_nodes,
        max_extended_size_integers=limits.max_input_nodes,
        max_extended_size_value=limits.max_output_bytes,
        max_offset_int_size=8,
        max_object_ref_size=8,
        max_offset_table_bytes=limits.max_output_bytes,
        max_syntax_pieces=limits.max_output_bytes,
        max_binary_facts=limits.max_output_bytes,
        max_conversion_nodes=limits.max_input_nodes,
        max_report_events=limits.max_report_entries,
        max_recovery_regions=limits.max_report_entries,
    )


def _promised_native(root: _ValueNode, limits: MaterializationLimits) -> NativeDocument:
    """Builds the promised native model of one parsed record (the input
    semantics the closure compares against)."""
    builder = PlistDocumentBuilder()

    def build(node: _ValueNode, depth: int) -> PlistValueRef:
        if depth > limits.max_depth:
            raise PlistMaterializationFailure(
                PlistMaterializationFailureKind.RESOURCE_LIMIT, name="depth"
            )
        kind = node.kind
        if kind is _ValueKind.DICT:
            refs = [(PlistKey(key), build(child, depth + 1)) for key, child in node.entries]
            value = PlistValue.dict(
                PlistDict(tuple(PlistDictEntry(key, ref) for key, ref in refs))
            )
            return builder.add(value)
        if kind is _ValueKind.ARRAY:
            value = PlistValue.array(
                PlistArray(tuple(build(element, depth + 1) for element in node.elements))
            )
            return builder.add(value)
        if kind is _ValueKind.STRING:
            return builder.add(PlistValue.string(node.string))
        if kind is _ValueKind.INTEGER:
            return builder.add(PlistValue.integer(PlistInteger(node.integer)))
        if kind is _ValueKind.REAL:
            return builder.add(PlistValue.real(node.real))
        if kind is _ValueKind.BOOLEAN:
            return builder.add(PlistValue.boolean(PlistBoolean(node.boolean)))
        if kind is _ValueKind.DATE:
            return builder.add(PlistValue.date(PlistDate.from_seconds(node.date_seconds)))
        if kind is _ValueKind.DATA:
            return builder.add(PlistValue.data(PlistData(node.data)))
        if kind is _ValueKind.UID:
            return builder.add(PlistValue.uid(PlistUid(node.uid)))
        raise PlistMaterializationFailure(
            PlistMaterializationFailureKind.UNREPRESENTABLE,
            detail=node.kind.value,
        )

    root_ref = build(root, 0)
    try:
        return builder.build(root_ref)
    except Exception:
        raise PlistMaterializationFailure(
            PlistMaterializationFailureKind.UNREPRESENTABLE,
            detail="arena",
        ) from None


def _verify_closure(
    promised: NativeDocument, document: PlistDocument
) -> None:
    """Reparse closure: the reparsed native model must equal the promised
    input semantics (RFC 0013 §10.3; materialization.rs:489-535)."""
    actual = document.document()
    if actual is None or actual != promised:
        raise PlistMaterializationFailure(
            PlistMaterializationFailureKind.FORMATION_FAILED,
            detail="closure",
        )


def _build_provenance(
    items: list, document: PlistDocument, style: _Style, limits: MaterializationLimits
) -> MaterializationProvenanceMap:
    """Pairs every recorded input item with its exact output origin
    (materialization.rs:1619-1720)."""
    from consema.document.materialization import MaterializationInputLocation as _Loc
    from consema.plist.projection import ValuePath, ValuePathSegment, ValuePathSegmentKind

    entries: list[MaterializationProvenanceEntry] = []
    authority = document.authority
    identity = document.snapshot_identity()
    for path, target in items:
        if len(entries) >= limits.max_provenance_entries:
            raise PlistMaterializationFailure(
                PlistMaterializationFailureKind.RESOURCE_LIMIT,
                name="provenance-entries",
            )
        segments = tuple(
            ValuePathSegment(
                ValuePathSegmentKind.SEQUENCE_ELEMENT
                if isinstance(step, int)
                else ValuePathSegmentKind.OBJECT_VALUE,
                step,
            )
            for step in path
        )
        value_path = ValuePath(segments)
        if style is _Style.BINARY:
            facts = document.binary_facts()
            assert facts is not None
            fact = facts.objects[target] if target < len(facts.objects) else None
            if fact is None:
                raise PlistMaterializationFailure(
                    PlistMaterializationFailureKind.FORMATION_FAILED
                )
            origin = MaterializedOrigin(
                snapshot=identity,
                node=authority.node_ref(fact.index, NodeRole.PLIST_VALUE),
                span=fact.span,
                relation=MaterializationRelation.DIRECT,
            )
        else:
            formed = document.formed_xml
            assert formed is not None
            span = formed.value_spans.get(target)
            if span is None:
                raise PlistMaterializationFailure(
                    PlistMaterializationFailureKind.FORMATION_FAILED
                )
            origin = MaterializedOrigin(
                snapshot=identity,
                node=authority.node_ref(target, NodeRole.PLIST_VALUE),
                span=span,
                relation=MaterializationRelation.DIRECT,
            )
        entries.append(
            MaterializationProvenanceEntry(
                input=_Loc.value(value_path),
                outputs=(origin,),
            )
        )
    return MaterializationProvenanceMap.new(entries, document.snapshot_identity(), limits)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def requested_profile(request: MaterializationRequest) -> PlistProfile:
    """Resolves the target profile (materialization.rs:77-89)."""
    if request.target_profile.id == "plist.xml" and request.target_profile.version == 1:
        return PlistProfile.XML_V1
    if request.target_profile.id == "plist.binary" and request.target_profile.version == 1:
        return PlistProfile.BINARY_V1
    raise PlistMaterializationFailure(PlistMaterializationFailureKind.UNSUPPORTED_PROFILE)


def validate_request(request: MaterializationRequest, profile: PlistProfile) -> _Style:
    """Style, newline, and encoding closure (materialization.rs:91-127;
    RFC 0013 §10.1-§10.2)."""
    from consema.document.source import SourceEncoding, SourceEncodingKind

    if (
        profile is PlistProfile.XML_V1
        and request.style.id == _STYLE_XML
        and request.style.version == 1
    ):
        style = _Style.XML
        if request.encoding != SourceEncoding.utf8():
            raise PlistMaterializationFailure(PlistMaterializationFailureKind.UNSUPPORTED_ENCODING)
        if request.newline is not NewlinePolicy.LF:
            raise PlistMaterializationFailure(PlistMaterializationFailureKind.UNSUPPORTED_NEWLINE)
        return style
    if (
        profile is PlistProfile.BINARY_V1
        and request.style.id == _STYLE_BINARY
        and request.style.version == 1
    ):
        style = _Style.BINARY
        if request.encoding.kind is not SourceEncodingKind.BINARY:
            raise PlistMaterializationFailure(PlistMaterializationFailureKind.UNSUPPORTED_ENCODING)
        if request.newline is not NewlinePolicy.NONE:
            raise PlistMaterializationFailure(PlistMaterializationFailureKind.UNSUPPORTED_NEWLINE)
        return style
    raise PlistMaterializationFailure(PlistMaterializationFailureKind.UNSUPPORTED_STYLE)


def materialize(
    value: PortableValue, request: MaterializationRequest
) -> MaterializationResult:
    """Materializes one ``plist.value-tree@1`` record into a new canonical
    plist document (RFC 0013 §10; materialization.rs:178-260).

    The requested style selects the target profile and representation:
    ``plist.xml-canonical@1`` produces a ``plist.xml@1`` Document and
    ``plist.binary-canonical@1`` a ``plist.binary@1`` Document. The
    generated bytes are reparsed under the promised Profile and the reparsed
    native model is compared to the promised input semantics; failure
    returns no target Document, no partial bytes, and no partial
    provenance."""
    analyzed: list = []
    try:
        complete = _materialize_complete(value, request, analyzed)
    except PlistMaterializationFailure as failure:
        # The date-kind name distinguishes the fractional-date spelling
        # (go/plist/materialization.go:125-140); the returned failure carries
        # the plist-owned ``plist.materialization.*@1`` codes directly.
        name = (
            "date"
            if failure.kind is PlistMaterializationFailureKind.FRACTIONAL_DATE
            else failure.name
        )
        return FailedMaterializationAttempt(
            failure=_PlistCodedFailure(
                _materialization_kind(failure), name=name, detail=failure.detail
            ),
            report=MaterializationReport(),
            analyzed_input_paths=tuple(analyzed),
        )
    except MaterializationFailure as failure:
        return FailedMaterializationAttempt(
            failure=failure,
            report=MaterializationReport(),
            analyzed_input_paths=tuple(analyzed),
        )
    return complete


def _materialization_kind(failure: PlistMaterializationFailure) -> MaterializationFailureKind:
    return {
        PlistMaterializationFailureKind.FRACTIONAL_DATE: MaterializationFailureKind.UNREPRESENTABLE,
        PlistMaterializationFailureKind.UNREPRESENTABLE: MaterializationFailureKind.UNREPRESENTABLE,
        PlistMaterializationFailureKind.RESOURCE_LIMIT: MaterializationFailureKind.RESOURCE_LIMIT,
        PlistMaterializationFailureKind.INVALID_REQUEST: MaterializationFailureKind.INVALID_REQUEST,
        PlistMaterializationFailureKind.UNSUPPORTED_PROFILE: MaterializationFailureKind.UNSUPPORTED_PROFILE,
        PlistMaterializationFailureKind.UNSUPPORTED_STYLE: MaterializationFailureKind.UNSUPPORTED_STYLE,
        PlistMaterializationFailureKind.UNSUPPORTED_ENCODING: MaterializationFailureKind.UNSUPPORTED_ENCODING,
        PlistMaterializationFailureKind.UNSUPPORTED_NEWLINE: MaterializationFailureKind.UNSUPPORTED_NEWLINE,
        PlistMaterializationFailureKind.FORMATION_FAILED: MaterializationFailureKind.FORMATION_FAILED,
    }[failure.kind]


def _materialize_complete(
    value: PortableValue,
    request: MaterializationRequest,
    analyzed: list,
) -> CompleteMaterialization:
    profile = requested_profile(request)
    style = validate_request(request, profile)
    root = parse_record(value, analyzed)
    limits = request.limits
    truncate = _record_truncate_policy(value)
    report_events: list = []
    if style is _Style.XML:
        bytes_, items = _serialize_xml(root, truncate, limits, report_events)
        selection = PlistEncodingSelection.profile_default()
        formed = parse_xml(bytes_, selection, _reparse_limits(limits, "utf8"))
        document = PlistDocument(
            authority=formed.authority,
            source=formed.source,
            profile=profile,
            _representation=PlistRepresentation.XML,
            _formation_status=formed.status,
            diagnostics=formed.diagnostics,
            native=formed.document,
            formed_xml=formed,
            root_node=formed.root_node,
        )
    else:
        bytes_, items = _serialize_binary(root, limits)
        from consema.plist.parser_binary import parse_binary

        formed = parse_binary(bytes_, PlistEncodingSelection.profile_default(), _reparse_limits(limits, "binary"))
        document = PlistDocument(
            authority=formed.authority,
            source=formed.source,
            profile=profile,
            _representation=PlistRepresentation.BINARY,
            _formation_status=formed.status,
            diagnostics=formed.diagnostics,
            native=formed.document,
            formed_binary=formed,
            root_node=formed.root_node,
        )
    if document.formation_status() is not FormationStatus.COMPLETE:
        raise PlistMaterializationFailure(
            PlistMaterializationFailureKind.FORMATION_FAILED,
            detail="reparse recovered",
        )
    promised = _promised_native(root, limits)
    _verify_closure(promised, document)
    provenance = _build_provenance(items, document, style, limits)
    fidelity = (
        MaterializationFidelity.TRANSFORMED
        if report_events
        else MaterializationFidelity.EXACT
    )
    report = MaterializationReport.new(report_events, limits)
    return CompleteMaterialization(
        document=document,
        fidelity=fidelity,
        report=report,
        provenance=provenance,
    )


def _record_truncate_policy(value: PortableValue) -> str | None:
    """The record's explicit truncation policy, when present."""
    fields = dict(value.as_object())
    policy = fields.get("truncate_policy")
    if policy is None:
        return None
    if policy.kind is not Kind.STRING or policy.as_string() != _TRUNCATE_POLICY:
        return None
    return _TRUNCATE_POLICY
