"""Materialization intent tests: the canonical
``xml.safe-canonical-document@1`` style (RFC 0012 §10, RFC 0004).

Authority: conformance/vectors/xml-1-0-safe-v1.json (case ids cited per
test); crates/consema-xml/src/materialization.rs (byte/registry
arbitration); RFC 0012 §10 (docs/rfcs/0012-xml-1.0-safe-profile-v1.md:
350-372): the exact generated bytes are reparsed under the promised
Profile and the reparsed native tree is compared to the promised input
semantics; failure returns no target Document and no partial output.

These tests are intent documents written before the Python toolchain
verification gate (docs/multi-language-implementation-plan.md §3/§7); no
gate is claimed to have passed.
"""

from __future__ import annotations

import pytest

from consema.core.value import PortableValue
from consema.document.ids import MaterializationStyleId, ProfileId
from consema.document.materialization import (
    FailedMaterializationAttempt,
    MaterializationFailureKind,
    MaterializationRequest,
    NewlinePolicy,
)
from consema.document.source import SourceEncoding

from consema.xml import materialize, parse, project_document, ProjectionRequest

from conftest import find_case, form_document


def _request():
    return MaterializationRequest.new(
        ProfileId.new("xml.1.0-safe", 1),
        MaterializationStyleId.new("xml.safe-canonical-document", 1),
    )


def _record(case) -> PortableValue:
    """The vector record converted to a PortableValue (the shared runners
    parse the vector JSON with the strict JSON profile and project the
    record field; conformance/vectors/xml-1-0-safe-v1.json:352-435)."""
    return _json_value(case["input"]["record"])


def _json_value(obj):
    if isinstance(obj, str):
        return PortableValue.string(obj)
    if isinstance(obj, bool):
        return PortableValue.boolean(obj)
    if isinstance(obj, int):
        return PortableValue.integer(obj)
    if isinstance(obj, list):
        return PortableValue.sequence([_json_value(item) for item in obj])
    if isinstance(obj, dict):
        return PortableValue.object([(key, _json_value(value)) for key, value in obj.items()])
    if obj is None:
        return PortableValue.null()
    raise AssertionError(f"unsupported json value {obj!r}")


# ---------------------------------------------------------------------------
# Golden vector transcriptions
# ---------------------------------------------------------------------------


def test_vector_canonical_round_trip(xml_vectors):
    """Golden transcription of ``xml.materialization.canonical-round-trip``
    (xml-1-0-safe-v1.json:351-388): the canonical style emits a final LF
    newline and double-quoted attributes."""
    case = find_case(xml_vectors, "xml.materialization.canonical-round-trip")
    result = materialize(_record(case), _request())
    assert result.document.render() == b'<root a="1">t</root>\n'
    assert result.fidelity.value == "Exact"


def test_vector_escapes_content(xml_vectors):
    """Golden transcription of ``xml.materialization.escapes-content``
    (xml-1-0-safe-v1.json:389-417): new literal content is XML-escaped,
    never interpolated as raw syntax (RFC 0012 §11, lines 393-395)."""
    case = find_case(xml_vectors, "xml.materialization.escapes-content")
    result = materialize(_record(case), _request())
    assert result.document.render() == b"<root>a &lt; b &amp; c</root>\n"


def test_vector_invalid_record_rejected(xml_vectors):
    """Golden transcription of ``xml.materialization.invalid-record-rejected``
    (xml-1-0-safe-v1.json:418-435): a record that is not
    ``xml.element-tree@1`` fails with the wire failure ``invalid-record``
    (the shared runners map InvalidRequest to that name,
    crates/consema-conformance/src/xml_v1.rs:860-871)."""
    case = find_case(xml_vectors, "xml.materialization.invalid-record-rejected")
    result = materialize(_record(case), _request())
    assert isinstance(result, FailedMaterializationAttempt)
    assert result.failure.kind is MaterializationFailureKind.INVALID_REQUEST
    assert result.failure.code == "core.materialization.invalid-request@1"


# ---------------------------------------------------------------------------
# Style contract (RFC 0012 §10)
# ---------------------------------------------------------------------------


def test_request_validation_rejects_foreign_contracts():
    """The canonical style accepts exactly the xml.1.0-safe@1 profile, the
    xml.safe-canonical-document@1 style, UTF-8/UTF-16 encodings, and
    LF/CRLF newlines (materialization.rs:90-107)."""
    record = _json_value({
        "record": "xml.element-tree@1",
        "root": {"expanded-name": {"namespace": None, "local": "root"}},
    })
    wrong_profile = MaterializationRequest.new(
        ProfileId.new("toml.1.0", 1),
        MaterializationStyleId.new("xml.safe-canonical-document", 1),
    )
    result = materialize(record, wrong_profile)
    assert result.failure.kind is MaterializationFailureKind.UNSUPPORTED_PROFILE
    wrong_style = MaterializationRequest.new(
        ProfileId.new("xml.1.0-safe", 1),
        MaterializationStyleId.new("toml.canonical-document", 1),
    )
    result = materialize(record, wrong_style)
    assert result.failure.kind is MaterializationFailureKind.UNSUPPORTED_STYLE


def test_utf16_output_carries_bom():
    """UTF-16 output always carries its corresponding BOM and a matching
    declaration (RFC 0012 §10, lines 364-366; materialization.rs:651-685).
    The declaration is emitted only when the record declares one; a
    UTF-16 output then forces the ``UTF-16`` spelling."""
    record = _json_value({
        "record": "xml.element-tree@1",
        "declaration": {"version": "1.0"},
        "root": {"expanded-name": {"namespace": None, "local": "root"}},
    })
    request = _request().with_encoding(SourceEncoding.utf16le())
    result = materialize(record, request)
    render = result.document.render()
    assert render.startswith(b"\xff\xfe")
    assert result.document.source().encoding_facts().selected == SourceEncoding.utf16le()
    declared = result.document.declaration()
    assert declared is not None
    assert declared.version == "1.0"
    assert declared.encoding[1] == "UTF-16"
    # A record without a declaration materializes without one (the vector
    # canonical-round-trip render has no declaration either).
    record = _json_value({
        "record": "xml.element-tree@1",
        "root": {"expanded-name": {"namespace": None, "local": "root"}},
    })
    result = materialize(record, _request())
    assert result.document.declaration() is None


def test_closure_verifies_reparsed_semantics():
    """Materialization reparses the exact generated bytes and compares the
    reparsed native tree to the promised input semantics
    (materialization.rs:912-1210); provenance covers every emitted value
    (RFC 0004 §8)."""
    doc = form_document(
        {"input": {"profile": "xml.1.0-safe@1", "source": '<root a="1"><child>t</child></root>'}}
    )
    projection = project_document(doc, ProjectionRequest.element_tree())
    result = materialize(projection.value, _request())
    assert result.document.status.value == "Complete"
    assert len(result.provenance.entries) > 0
    for entry in result.provenance.entries:
        for origin in entry.outputs:
            assert origin.snapshot == result.document.snapshot_identity()
