"""Canonical `hcl.canonical-document@1` materialization (RFC 0014 §9).

Materialization consumes one validated `hcl.body@1` record and creates a
new `hcl.native@1` or `hcl.tfvars@1` Document. It is not a formatter for an
existing source: the input is the projected body record, the output is a
new snapshot whose complete native model equals the promised input
semantics.

The input must be an Object record `{ "record": "hcl.body@1", "items":
[<item>, ...] }`; an item is an Object with a string `kind`
(`attribute`/`block`). A value record is an Object with a string `kind`
(string/integer/real/boolean/null/tuple/object/expression), and the RFC
0014 §8.2 typed member itself is also accepted as the attribute `value`
(raw string, integer, real, boolean, null, tuple, object PortableValue or
an `hcl.expression@1` record object). Attribute names and block types must
be valid UAX #31 identifiers; a body with two attributes of the same name
is unrepresentable, because the per-body duplicate-attribute rule of RFC
0014 §3 admits no Complete document with duplicates.

The style emits UTF-8 without BOM with LF line endings, two-space
indentation per body nesting level, `name = value` attributes, block
headers as `type "label" {`, minimal deterministic string escapes, numbers
in canonical decimal spelling, one-item-per-line constructor layout with
empty constructors single-line, `=` object keys, always-quoted labels, and
`hcl.expression@1` values emitting their canonical text verbatim.

Every style validates the complete input before proportional allocation,
encodes, reparses the exact generated bytes under the promised Profile, and
compares the reparsed native model to the promised input semantics —
numbers by canonical-decimal value equality, everything else by structural
equality, `hcl.expression@1` values by structural equality plus
fingerprint equality (RFC 0014 §6, §9). Failure returns no target
Document, partial bytes, or partial provenance.

Authority (language-neutral first; Rust only for byte/registry
arbitration): crates/consema-hcl/src/materialization.rs — the record
contract materialization.rs:9-103, request validation
materialization.rs:266-285, the canonical layout materialization.rs:105-121
and writer materialization.rs:1133-1333, decimal rendering
materialization.rs:1341-1494, the expression promise
materialization.rs:1084-1120, the closure walk materialization.rs:1770-...,
and the failure mapping materialization.rs:124-137.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field

from consema.core.value import Decimal, Kind, PortableValue
from consema.document.ids import MaterializationStyleId, ProfileId
from consema.document.materialization import (
    CompleteMaterialization,
    FailedMaterializationAttempt,
    MaterializationFidelity,
    MaterializationInputLocation,
    MaterializationProvenanceEntry,
    MaterializationProvenanceMap,
    MaterializationRelation,
    MaterializationReport,
    MaterializationRequest,
    MaterializationResult,
    MaterializedOrigin,
    NewlinePolicy,
)
from consema.document.source import SourceEncoding
from consema.document.structural import FormationStatus, NodeRef, Span
from consema.hcl.document import HclDocument, parse as parse_document
from consema.hcl.errors import HclMaterializationFailure, HclMaterializationFailureKind
from consema.hcl.expression import (
    HclExpression,
    HclExpressionKindName,
    HeredocMode,
    HclLiteralValue,
    is_literal_complete,
    literal_value,
    structural_fingerprint,
    structural_fingerprint_hex,
    canonical_decimal,
)
from consema.hcl.kinds import HclProfile, is_identifier_continue, is_identifier_start
from consema.hcl.limits import HclParseLimits
from consema.hcl.projection import (
    ValuePath,
    ValuePathSegment,
    ValuePathSegmentKind,
)

STYLE_CANONICAL = "hcl.canonical-document"
BODY_RECORD = "hcl.body@1"
EXPRESSION_RECORD = "hcl.expression@1"
SENTINEL_ATTRIBUTE = "expr"

_KIND_FAMILY_NAMES = frozenset(
    (
        "number",
        "boolean",
        "null",
        "template",
        "function-call",
        "variable",
        "unary",
        "binary",
        "conditional",
        "for",
        "tuple",
        "object",
        "parenthesized",
    )
)


class _Target(enum.Enum):
    """The canonical materialization target (materialization.rs:194-201)."""

    NATIVE = "native"
    TFVARS = "tfvars"


def materialize(
    value: PortableValue, request: MaterializationRequest
) -> MaterializationResult:
    """Materializes one `hcl.body@1` record into a new canonical HCL
    document (RFC 0014 §9; materialization.rs:213-226)."""
    analyzed: list[ValuePath] = []
    try:
        complete = _materialize_complete(value, request, analyzed)
    except HclMaterializationFailure as failure:
        return FailedMaterializationAttempt(
            failure=_shared_failure(failure),
            report=MaterializationReport(),
            analyzed_input_paths=tuple(analyzed),
        )
    return complete


def _shared_failure(failure: HclMaterializationFailure):
    """The shared MaterializationFailure surface consumed by the failure
    algebra (RFC 0004 §7)."""
    from consema.document.materialization import (
        MaterializationFailure,
        MaterializationFailureKind,
    )

    kind = {
        HclMaterializationFailureKind.UNSUPPORTED_PROFILE: MaterializationFailureKind.UNSUPPORTED_PROFILE,
        HclMaterializationFailureKind.UNSUPPORTED_STYLE: MaterializationFailureKind.UNSUPPORTED_STYLE,
        HclMaterializationFailureKind.UNSUPPORTED_ENCODING: MaterializationFailureKind.UNSUPPORTED_ENCODING,
        HclMaterializationFailureKind.UNSUPPORTED_NEWLINE: MaterializationFailureKind.UNSUPPORTED_NEWLINE,
        HclMaterializationFailureKind.RESOURCE_LIMIT: MaterializationFailureKind.RESOURCE_LIMIT,
        HclMaterializationFailureKind.UNREPRESENTABLE: MaterializationFailureKind.UNREPRESENTABLE,
        HclMaterializationFailureKind.INVALID_REQUEST: MaterializationFailureKind.INVALID_REQUEST,
        HclMaterializationFailureKind.FORMATION_FAILED: MaterializationFailureKind.FORMATION_FAILED,
    }.get(failure.kind, MaterializationFailureKind.INVALID_REQUEST)
    return MaterializationFailure(kind, name=failure.resource_name, detail=failure.detail)


def materialization_failure_code(failure) -> str:
    """The suite-published failure code of one shared MaterializationFailure
    (RFC 0014 §9; crates/consema-conformance/src/hcl_v1.rs:1611-1616):
    Unrepresentable maps to hcl.materialization.unrepresentable@1,
    ResourceLimit to hcl.materialization.resource-limit@1, InvalidRequest
    to the published spelling "invalid-record"."""
    from consema.document.materialization import MaterializationFailureKind

    if failure.kind is MaterializationFailureKind.UNREPRESENTABLE:
        return "hcl.materialization.unrepresentable@1"
    if failure.kind is MaterializationFailureKind.RESOURCE_LIMIT:
        return "hcl.materialization.resource-limit@1"
    if failure.kind is MaterializationFailureKind.INVALID_REQUEST:
        return "invalid-record"
    return failure.code


def _materialize_complete(
    value: PortableValue,
    request: MaterializationRequest,
    analyzed: list[ValuePath],
) -> CompleteMaterialization:
    target = _validate_request(request)
    limits = request.limits
    record = _Record.validate(value, request, analyzed)
    writer = _Writer(limits)
    _write_body(writer, record.body, 0)
    bytes_ = writer.finish()
    profile = (
        HclProfile.TFVARS_V1 if target is _Target.TFVARS else HclProfile.NATIVE_V1
    )
    document = parse_document(bytes_, profile, limits=_parse_limits(limits))
    if document.formation_status() is not FormationStatus.COMPLETE:
        raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
    provenance = _verify_closure(record, document, limits)
    return CompleteMaterialization(
        document=document,
        fidelity=MaterializationFidelity.EXACT,
        report=MaterializationReport(),
        provenance=provenance,
    )


def _validate_request(request: MaterializationRequest) -> _Target:
    """Validates the request against the frozen style contract (RFC 0014
    §9; materialization.rs:266-285)."""
    profile = request.target_profile
    style = request.style
    if profile.id == "hcl.native" and profile.version == 1 and style.id == STYLE_CANONICAL and style.version == 1:
        target = _Target.NATIVE
    elif profile.id == "hcl.tfvars" and profile.version == 1 and style.id == STYLE_CANONICAL and style.version == 1:
        target = _Target.TFVARS
    elif profile.id not in ("hcl.native", "hcl.tfvars") or profile.version != 1:
        raise HclMaterializationFailure(HclMaterializationFailureKind.UNSUPPORTED_PROFILE)
    else:
        raise HclMaterializationFailure(HclMaterializationFailureKind.UNSUPPORTED_STYLE)
    if request.encoding != SourceEncoding.utf8():
        raise HclMaterializationFailure(HclMaterializationFailureKind.UNSUPPORTED_ENCODING)
    if request.newline is not NewlinePolicy.LF:
        raise HclMaterializationFailure(HclMaterializationFailureKind.UNSUPPORTED_NEWLINE)
    return target


def _parse_limits(limits) -> HclParseLimits:
    """Parse limits for the closure reparse, derived from the request so a
    bounded input cannot fail its own closure (materialization.rs:287-328)."""
    from consema.document.limits import ParseLimits

    return HclParseLimits(
        common=ParseLimits(
            max_source_bytes=limits.max_output_bytes,
            max_nesting_depth=limits.max_depth + 2,
            max_token_count=limits.max_output_bytes,
            max_node_count=limits.max_output_bytes,
            max_diagnostics=limits.max_report_entries,
        ),
        max_decoded_utf8_bytes=limits.max_output_bytes * 3,
        max_decoded_scalars=limits.max_output_bytes,
        max_body_depth=limits.max_depth + 2,
        max_expression_depth=limits.max_depth + 2,
        max_template_depth=limits.max_depth + 2,
        max_attribute_count=limits.max_input_nodes,
        max_block_count=limits.max_input_nodes,
        max_label_count=limits.max_input_nodes,
        max_body_item_count=limits.max_input_nodes * 2,
        max_identifier_len=limits.max_output_bytes,
        max_string_len=limits.max_output_bytes,
        max_number_digits=limits.max_output_bytes,
        max_template_len=limits.max_output_bytes,
        max_template_interpolations=limits.max_input_nodes,
        max_heredoc_lines=limits.max_output_bytes,
        max_heredoc_bytes=limits.max_output_bytes,
        max_tuple_elements=limits.max_input_nodes,
        max_object_entries=limits.max_input_nodes,
        max_for_extent=limits.max_input_nodes,
        max_recovery_regions=limits.max_report_entries,
        max_error_regions=limits.max_report_entries,
        max_syntax_pieces=limits.max_output_bytes,
        max_report_events=limits.max_report_entries,
    )


# ---------------------------------------------------------------------------
# Record validation
# ---------------------------------------------------------------------------


class _Validator:
    """Input node budget accounting during validation (materialization.rs:
    497-520)."""

    def __init__(self, limits) -> None:
        self.nodes = 0
        self.limits = limits

    def step(self) -> None:
        self.nodes += 1
        if self.nodes > self.limits.max_input_nodes:
            raise HclMaterializationFailure(
                HclMaterializationFailureKind.RESOURCE_LIMIT,
                resource_name="input-nodes",
            )


@dataclass(frozen=True, slots=True)
class _ValueNode:
    """One validated value record with its kind semantics."""

    kind: str
    text: str = ""
    flag: bool = False
    elements: tuple[_ValueNode, ...] = ()
    entries: tuple[tuple[str, _ValueNode], ...] = ()
    expression: HclExpression | None = None
    expression_text: str = ""


@dataclass(frozen=True, slots=True)
class _BodyItem:
    """One validated body item."""

    kind: str
    name: str = ""
    value: _ValueNode | None = None
    block_type: str = ""
    labels: tuple[str, ...] = ()
    body: _Body | None = None


@dataclass(frozen=True, slots=True)
class _Body:
    """One validated body: ordered attributes and blocks."""

    items: tuple[_BodyItem, ...]


@dataclass(frozen=True, slots=True)
class _Record:
    """One validated `hcl.body@1` record."""

    body: _Body

    @classmethod
    def validate(
        cls, value: PortableValue, request: MaterializationRequest, analyzed: list[ValuePath]
    ) -> _Record:
        analyzed.append(ValuePath.root())
        if value.kind is not Kind.OBJECT:
            raise HclMaterializationFailure(
                HclMaterializationFailureKind.INVALID_REQUEST,
                detail="input record is not an object",
            )
        record_value = _field(value, "record", "input record is missing the record member")
        if record_value is None or record_value.kind is not Kind.STRING:
            raise HclMaterializationFailure(
                HclMaterializationFailureKind.INVALID_REQUEST,
                detail="input record is missing the record member",
            )
        if record_value.as_string() != BODY_RECORD:
            raise HclMaterializationFailure(
                HclMaterializationFailureKind.INVALID_REQUEST,
                detail="input record is not hcl.body@1",
            )
        tfvars = request.target_profile == ProfileId.new("hcl.tfvars", 1)
        validator = _Validator(request.limits)
        body = _validate_body(value, ValuePath.root(), validator, analyzed, tfvars, 0)
        return _Record(body=body)


def _field(value: PortableValue, name: str, missing_detail: str) -> PortableValue | None:
    for key, member in value.as_object():
        if key == name:
            return member
    raise HclMaterializationFailure(
        HclMaterializationFailureKind.INVALID_REQUEST, detail=missing_detail
    )


def _validate_body(
    value: PortableValue,
    path: ValuePath,
    validator: _Validator,
    analyzed: list[ValuePath],
    tfvars: bool,
    depth: int,
) -> _Body:
    if depth > validator.limits.max_depth:
        raise HclMaterializationFailure(
            HclMaterializationFailureKind.RESOURCE_LIMIT, resource_name="input-depth"
        )
    items_value = _field(value, "items", "input body record is missing the items member")
    if items_value.kind is not Kind.SEQUENCE:
        raise HclMaterializationFailure(
            HclMaterializationFailureKind.UNREPRESENTABLE,
            detail="body items must be a sequence",
        )
    items = items_value.as_sequence()
    out: list[_BodyItem] = []
    names: set[str] = set()
    for index, item in enumerate(items):
        item_path = path.child(ValuePathSegment(ValuePathSegmentKind.SEQUENCE_ELEMENT, index))
        validator.step()
        analyzed.append(item_path)
        if item.kind is not Kind.OBJECT:
            raise HclMaterializationFailure(
                HclMaterializationFailureKind.UNREPRESENTABLE,
                detail="body item is not an object",
            )
        kind_value = _field(item, "kind", "body item is missing the kind member")
        if kind_value.kind is not Kind.STRING:
            raise HclMaterializationFailure(
                HclMaterializationFailureKind.UNREPRESENTABLE,
                detail="body item kind is not a string",
            )
        kind = kind_value.as_string()
        if kind == "attribute":
            name_value = _field(item, "name", "attribute item is missing the name member")
            if name_value.kind is not Kind.STRING:
                raise HclMaterializationFailure(
                    HclMaterializationFailureKind.UNREPRESENTABLE,
                    detail="attribute name is not a string",
                )
            name = name_value.as_string()
            if not _is_plain_identifier(name):
                raise HclMaterializationFailure(
                    HclMaterializationFailureKind.UNREPRESENTABLE,
                    detail="attribute name is not a valid identifier",
                )
            if name in names:
                raise HclMaterializationFailure(
                    HclMaterializationFailureKind.UNREPRESENTABLE,
                    detail="duplicate attribute name in one body",
                )
            names.add(name)
            value_member = _field(item, "value", "attribute item is missing the value member")
            value_node = _validate_value(value_member, request_limits(validator), analyzed)
            out.append(_BodyItem(kind="attribute", name=name, value=value_node))
        elif kind == "block":
            if tfvars:
                raise HclMaterializationFailure(
                    HclMaterializationFailureKind.UNREPRESENTABLE,
                    detail="block in tfvars target",
                )
            type_value = _field(item, "type", "block item is missing the type member")
            if type_value.kind is not Kind.STRING:
                raise HclMaterializationFailure(
                    HclMaterializationFailureKind.UNREPRESENTABLE,
                    detail="block type is not a string",
                )
            block_type = type_value.as_string()
            if not _is_plain_identifier(block_type):
                raise HclMaterializationFailure(
                    HclMaterializationFailureKind.UNREPRESENTABLE,
                    detail="block type is not a valid identifier",
                )
            labels_value = _field(item, "labels", "block item is missing the labels member")
            if labels_value.kind is not Kind.SEQUENCE:
                raise HclMaterializationFailure(
                    HclMaterializationFailureKind.UNREPRESENTABLE,
                    detail="block labels must be a sequence",
                )
            labels = []
            for label in labels_value.as_sequence():
                if label.kind is not Kind.STRING:
                    raise HclMaterializationFailure(
                        HclMaterializationFailureKind.UNREPRESENTABLE,
                        detail="block label is not a string",
                    )
                labels.append(label.as_string())
            body_member = _field(item, "body", "block item is missing the body member")
            body_path = item_path.child(ValuePathSegment(ValuePathSegmentKind.OBJECT_VALUE, "body"))
            nested = _validate_body(body_member, body_path, validator, analyzed, tfvars, depth + 1)
            out.append(
                _BodyItem(
                    kind="block",
                    block_type=block_type,
                    labels=tuple(labels),
                    body=nested,
                )
            )
        else:
            raise HclMaterializationFailure(
                HclMaterializationFailureKind.UNREPRESENTABLE,
                detail=f"unknown body item kind {kind!r}",
            )
    return _Body(items=tuple(out))


def request_limits(validator: _Validator):
    return validator.limits


def _validate_value(
    value: PortableValue, limits, analyzed: list[ValuePath]
) -> _ValueNode:
    if value.kind is Kind.OBJECT and _looks_like_expression_record(value):
        # The raw typed member form of a derived expression: the
        # `hcl.expression@1` record object itself (materialization.rs:61-64).
        return _validate_expression_record(value, limits)
    if value.kind is Kind.OBJECT and _looks_like_value_record(value):
        kind_value = _field(value, "kind", "value record is missing the kind member")
        kind = kind_value.as_string()
        if kind == "string":
            text_value = _field(value, "text", "string value is missing the text member")
            if text_value.kind is not Kind.STRING:
                raise HclMaterializationFailure(
                    HclMaterializationFailureKind.UNREPRESENTABLE,
                    detail="string text is not a string",
                )
            return _ValueNode(kind="string", text=text_value.as_string())
        if kind == "integer":
            int_value = _field(value, "value", "integer value is missing the value member")
            if int_value.kind is not Kind.INTEGER:
                raise HclMaterializationFailure(
                    HclMaterializationFailureKind.UNREPRESENTABLE,
                    detail="integer value is not an integer",
                )
            return _ValueNode(kind="integer", text=str(int_value.as_integer()))
        if kind == "real":
            real_value = _field(value, "value", "real value is missing the value member")
            return _ValueNode(kind="real", text=_real_spelling(real_value))
        if kind == "boolean":
            bool_value = _field(value, "value", "boolean value is missing the value member")
            if bool_value.kind is not Kind.BOOLEAN:
                raise HclMaterializationFailure(
                    HclMaterializationFailureKind.UNREPRESENTABLE,
                    detail="boolean value is not a boolean",
                )
            return _ValueNode(kind="boolean", flag=bool_value.as_boolean())
        if kind == "null":
            return _ValueNode(kind="null")
        if kind == "tuple":
            elements_value = _field(value, "elements", "tuple value is missing the elements member")
            if elements_value.kind is not Kind.SEQUENCE:
                raise HclMaterializationFailure(
                    HclMaterializationFailureKind.UNREPRESENTABLE,
                    detail="tuple elements are not a sequence",
                )
            elements = tuple(
                _validate_value(element, limits, analyzed)
                for element in elements_value.as_sequence()
            )
            return _ValueNode(kind="tuple", elements=elements)
        if kind == "object":
            entries_value = _field(value, "entries", "object value is missing the entries member")
            if entries_value.kind is not Kind.SEQUENCE:
                raise HclMaterializationFailure(
                    HclMaterializationFailureKind.UNREPRESENTABLE,
                    detail="object entries are not a sequence",
                )
            entries = []
            for entry in entries_value.as_sequence():
                if entry.kind is not Kind.SEQUENCE or len(entry.as_sequence()) != 2:
                    raise HclMaterializationFailure(
                        HclMaterializationFailureKind.UNREPRESENTABLE,
                        detail="object entry is not a key/value pair",
                    )
                key, entry_value = entry.as_sequence()
                if key.kind is not Kind.STRING:
                    raise HclMaterializationFailure(
                        HclMaterializationFailureKind.UNREPRESENTABLE,
                        detail="object entry key is not a string",
                    )
                entries.append(
                    (
                        key.as_string(),
                        _validate_value(entry_value, limits, analyzed),
                    )
                )
            return _ValueNode(kind="object", entries=tuple(entries))
        if kind == "expression":
            expression_value = _field(
                value, "expression", "expression value is missing the expression member"
            )
            return _validate_expression_record(expression_value, limits)
        raise HclMaterializationFailure(
            HclMaterializationFailureKind.UNREPRESENTABLE,
            detail=f"unknown value kind {kind!r}",
        )
    if value.kind is Kind.STRING:
        return _ValueNode(kind="string", text=value.as_string())
    if value.kind is Kind.INTEGER:
        return _ValueNode(kind="integer", text=str(value.as_integer()))
    if value.kind in (Kind.DECIMAL, Kind.BINARY_FLOAT64, Kind.BINARY_FLOAT32):
        return _ValueNode(kind="real", text=_real_spelling(value))
    if value.kind is Kind.BOOLEAN:
        return _ValueNode(kind="boolean", flag=value.as_boolean())
    if value.kind is Kind.NULL:
        return _ValueNode(kind="null")
    if value.kind is Kind.SEQUENCE:
        elements = tuple(
            _validate_value(element, limits, analyzed) for element in value.as_sequence()
        )
        return _ValueNode(kind="tuple", elements=elements)
    if value.kind is Kind.ENTRY_MAPPING:
        entries = []
        for key, entry_value in value.as_entry_mapping():
            if key.kind is not Kind.STRING:
                raise HclMaterializationFailure(
                    HclMaterializationFailureKind.UNREPRESENTABLE,
                    detail="object entry key is not a string",
                )
            entries.append((key.as_string(), _validate_value(entry_value, limits, analyzed)))
        return _ValueNode(kind="object", entries=tuple(entries))
    raise HclMaterializationFailure(
        HclMaterializationFailureKind.UNREPRESENTABLE,
        detail=f"unrepresentable value kind {value.kind.value}",
    )


def _looks_like_value_record(value: PortableValue) -> bool:
    names = {key for key, _ in value.as_object()}
    return "kind" in names


def _looks_like_expression_record(value: PortableValue) -> bool:
    names = {key for key, _ in value.as_object()}
    return "record" in names and "text" in names


def _real_spelling(value: PortableValue) -> str:
    if value.kind is Kind.DECIMAL:
        return render_decimal(value.as_decimal())
    if value.kind is Kind.BINARY_FLOAT64:
        spelling = _double_to_canonical_decimal(value.as_binary_float64())
        if spelling is None:
            raise HclMaterializationFailure(
                HclMaterializationFailureKind.UNREPRESENTABLE,
                detail="non-finite real payload",
            )
        return spelling
    spelling = _double_to_canonical_decimal(value.as_binary_float32())
    if spelling is None:
        raise HclMaterializationFailure(
            HclMaterializationFailureKind.UNREPRESENTABLE,
            detail="non-finite real payload",
        )
    return spelling


def _validate_expression_record(value: PortableValue, limits) -> _ValueNode:
    record_value = _field(value, "record", "expression record is missing the record member")
    if record_value.kind is not Kind.STRING or record_value.as_string() != EXPRESSION_RECORD:
        raise HclMaterializationFailure(
            HclMaterializationFailureKind.INVALID_REQUEST,
            detail="expression record is not hcl.expression@1",
        )
    kind_value = _field(value, "kind", "expression record is missing the kind member")
    text_value = _field(value, "text", "expression record is missing the text member")
    if kind_value.kind is not Kind.STRING or text_value.kind is not Kind.STRING:
        raise HclMaterializationFailure(
            HclMaterializationFailureKind.INVALID_REQUEST,
            detail="expression record members are not strings",
        )
    kind = kind_value.as_string()
    if kind not in _KIND_FAMILY_NAMES:
        raise HclMaterializationFailure(
            HclMaterializationFailureKind.INVALID_REQUEST,
            detail="expression kind spelling is not in the closed set",
        )
    text = text_value.as_string()
    if not text:
        raise HclMaterializationFailure(
            HclMaterializationFailureKind.INVALID_REQUEST,
            detail="expression text is empty",
        )
    ast = _promised_expression_parse(text, limits)
    if ast.kind.kind_family() != kind:
        raise HclMaterializationFailure(
            HclMaterializationFailureKind.INVALID_REQUEST,
            detail="expression kind does not match the parsed text",
        )
    fingerprint_value = None
    for key, member in value.as_object():
        if key == "fingerprint":
            fingerprint_value = member
    if fingerprint_value is not None:
        if fingerprint_value.kind is not Kind.STRING:
            raise HclMaterializationFailure(
                HclMaterializationFailureKind.INVALID_REQUEST,
                detail="expression fingerprint is not a string",
            )
        promised = structural_fingerprint_hex(ast)
        if fingerprint_value.as_string() != promised:
            raise HclMaterializationFailure(
                HclMaterializationFailureKind.INVALID_REQUEST,
                detail="expression fingerprint does not match",
            )
    return _ValueNode(kind="expression", expression=ast, expression_text=text)


def _promised_expression_parse(text: str, limits) -> HclExpression:
    """Parses one promised expression text standalone; the wrapper source
    is exactly `text.len() + 8` bytes (materialization.rs:1084-1120)."""
    source = f"{SENTINEL_ATTRIBUTE} = {text}\n".encode("utf-8")
    try:
        document = parse_document(source, HclProfile.NATIVE_V1, limits=_expression_limits(text, limits))
    except Exception:
        raise HclMaterializationFailure(
            HclMaterializationFailureKind.RESOURCE_LIMIT, resource_name="input-depth"
        ) from None
    if document.formation_status() is not FormationStatus.COMPLETE:
        raise HclMaterializationFailure(
            HclMaterializationFailureKind.INVALID_REQUEST,
            detail="expression text does not parse",
        )
    items = document.body.items
    if len(items) != 1:
        raise HclMaterializationFailure(
            HclMaterializationFailureKind.INVALID_REQUEST,
            detail="expression text does not parse",
        )
    attribute = items[0].as_attribute()
    if attribute is None or attribute.name != SENTINEL_ATTRIBUTE:
        raise HclMaterializationFailure(
            HclMaterializationFailureKind.INVALID_REQUEST,
            detail="expression text does not parse",
        )
    return attribute.expression


def _expression_limits(text: str, limits) -> HclParseLimits:
    from consema.document.limits import ParseLimits

    source = len(text.encode("utf-8")) + 8
    return HclParseLimits(
        common=ParseLimits(
            max_source_bytes=source,
            max_nesting_depth=limits.max_depth + 2,
            max_token_count=source * 2,
            max_node_count=source * 2,
            max_diagnostics=limits.max_report_entries,
        ),
        max_decoded_utf8_bytes=source * 3,
        max_decoded_scalars=source,
        max_body_depth=4,
        max_expression_depth=limits.max_depth + 2,
        max_template_depth=limits.max_depth + 2,
        max_attribute_count=8,
        max_block_count=8,
        max_label_count=8,
        max_body_item_count=16,
        max_identifier_len=source,
        max_string_len=source,
        max_number_digits=limits.max_output_bytes,
        max_template_len=source,
        max_template_interpolations=source,
        max_heredoc_lines=source,
        max_heredoc_bytes=source,
        max_tuple_elements=source,
        max_object_entries=source,
        max_for_extent=source,
        max_recovery_regions=limits.max_report_entries,
        max_error_regions=limits.max_report_entries,
        max_syntax_pieces=source * 2,
        max_report_events=limits.max_report_entries,
    )


# ---------------------------------------------------------------------------
# Canonical layout (RFC 0014 §9; materialization.rs:105-1333)
# ---------------------------------------------------------------------------


class _Writer:
    """The canonical emitter: a bounded output String with checked appends
    (materialization.rs:1133-1171)."""

    def __init__(self, limits) -> None:
        self.out: list[str] = []
        self.total = 0
        self.limits = limits

    def push(self, text: str) -> None:
        self.total += len(text.encode("utf-8"))
        if self.total > self.limits.max_output_bytes:
            raise HclMaterializationFailure(
                HclMaterializationFailureKind.RESOURCE_LIMIT,
                resource_name="output-bytes",
            )
        self.out.append(text)

    def indent(self, depth: int) -> None:
        for _ in range(depth):
            self.push("  ")

    def push_quoted(self, text: str) -> None:
        self.push('"')
        self.push(escape_text(text))
        self.push('"')

    def finish(self) -> bytes:
        return "".join(self.out).encode("utf-8")


def _write_body(writer: _Writer, body: _Body, depth: int) -> None:
    for item in body.items:
        if item.kind == "attribute":
            writer.indent(depth)
            writer.push(item.name)
            writer.push(" = ")
            _write_value(writer, item.value, depth)
            writer.push("\n")
        else:
            writer.indent(depth)
            writer.push(item.block_type)
            for label in item.labels:
                writer.push(" ")
                writer.push_quoted(label)
            writer.push(" {\n")
            _write_body(writer, item.body, depth + 1)
            writer.indent(depth)
            writer.push("}\n")


def _write_value(writer: _Writer, value: _ValueNode, depth: int) -> None:
    kind = value.kind
    if kind == "string":
        writer.push_quoted(value.text)
    elif kind in ("integer", "real"):
        writer.push(value.text)
    elif kind == "boolean":
        writer.push("true" if value.flag else "false")
    elif kind == "null":
        writer.push("null")
    elif kind == "tuple":
        if not value.elements:
            writer.push("[]")
            return
        writer.push("[\n")
        last = len(value.elements) - 1
        for index, element in enumerate(value.elements):
            writer.indent(depth + 1)
            _write_value(writer, element, depth + 1)
            writer.push("\n" if index == last else ",\n")
        writer.indent(depth)
        writer.push("]")
    elif kind == "object":
        if not value.entries:
            writer.push("{}")
            return
        writer.push("{\n")
        last = len(value.entries) - 1
        for index, (key, entry_value) in enumerate(value.entries):
            writer.indent(depth + 1)
            _write_object_key(writer, key)
            writer.push(" = ")
            _write_value(writer, entry_value, depth + 1)
            writer.push("\n" if index == last else ",\n")
        writer.indent(depth)
        writer.push("}")
    else:
        writer.push(value.expression_text)


def _write_object_key(writer: _Writer, key: str) -> None:
    """One object key: bare for a plain identifier other than the
    contextual `for`, else quoted (materialization.rs:1255-1264)."""
    if _is_plain_identifier(key) and key != "for":
        writer.push(key)
    else:
        writer.push_quoted(key)


def _is_plain_identifier(text: str) -> bool:
    """Whether one text is a valid UAX #31 identifier with the frozen
    hyphen continuation and the underscore exclusion at the start (RFC
    0014 §4.1, §12 D-4; materialization.rs:1266-1278)."""
    if not text:
        return False
    first = text[0]
    if first == "_" or not is_identifier_start(first):
        return False
    for character in text[1:]:
        if not (is_identifier_continue(character) or character == "-"):
            return False
    return True


def _is_escaped_control(character: str) -> bool:
    value = ord(character)
    return value < 0x20 or 0x7F <= value <= 0x9F


def escape_text(text: str) -> str:
    """Escapes one string with the minimal deterministic escape set (RFC
    0014 §9): `\\n`, `\\r`, `\\t`, `\\"`, `\\\\`, `\\uNNNN` for control
    characters, and the `$${`/`%%{` doubling for the template openers
    (materialization.rs:1280-1333)."""
    out: list[str] = []
    index = 0
    while index < len(text):
        byte = text[index]
        if byte in ("$", "%"):
            run = 1
            while index + run < len(text) and text[index + run] == byte:
                run += 1
            doubled = index + run < len(text) and text[index + run] == "{"
            out.append(byte * (run + (1 if doubled else 0)))
            index += run
        else:
            if byte == '"':
                out.append('\\"')
            elif byte == "\\":
                out.append("\\\\")
            elif byte == "\n":
                out.append("\\n")
            elif byte == "\r":
                out.append("\\r")
            elif byte == "\t":
                out.append("\\t")
            elif _is_escaped_control(byte):
                out.append(f"\\u{ord(byte):04x}")
            else:
                out.append(byte)
            index += 1
    return "".join(out)


def render_decimal(decimal: Decimal) -> str:
    """Renders one normalized decimal as its plain canonical spelling: the
    coefficient digits with the exponent folded into the decimal point
    position, `"0"` for zero (RFC 0014 §9; materialization.rs:1341-1428)."""
    coefficient = decimal.coefficient
    if coefficient == 0:
        return "0"
    digits = str(coefficient)
    exponent = decimal.exponent
    if exponent == 0:
        return digits
    if exponent > 0:
        return digits + ("0" * exponent)
    fraction = -exponent
    signed = digits.startswith("-")
    magnitude = digits[1:] if signed else digits
    if fraction < len(magnitude):
        point = len(magnitude) - fraction
        out = "-" if signed else ""
        out += magnitude[:point] + "." + magnitude[point:]
        return out
    zeros = fraction - len(magnitude)
    out = "-" if signed else ""
    out += "0." + ("0" * zeros) + magnitude
    return out


def _double_to_canonical_decimal(bits: int) -> str | None:
    """Exact canonical decimal spelling of one binary64 datum; None for
    NaN and infinity, which the HCL number grammar cannot express
    (materialization.rs:1450-1494)."""
    if bits >> 63:
        sign = 1
    else:
        sign = 0
    exponent_bits = (bits >> 52) & 0x7FF
    fraction = bits & 0xFFFFFFFFFFFFF
    if exponent_bits == 0:
        if fraction == 0:
            return "0"
        mantissa = fraction
        exponent = -1074
    elif exponent_bits == 0x7FF:
        return None
    else:
        mantissa = fraction | 0x10000000000000
        exponent = exponent_bits - 1075
    if exponent >= 0:
        digits = str(mantissa << exponent)
    else:
        magnitude = -exponent
        digits = str(mantissa * (5**magnitude))
        digits = _place_decimal_point(digits, magnitude)
    canonical = canonical_decimal(digits)
    if canonical is None:
        return None
    if sign and canonical != "0":
        canonical = "-" + canonical
    return canonical


def _place_decimal_point(digits: str, fraction: int) -> str:
    if fraction < len(digits):
        point = len(digits) - fraction
        return digits[:point] + "." + digits[point:]
    return "0." + ("0" * (fraction - len(digits))) + digits


# ---------------------------------------------------------------------------
# Closure verification and provenance (materialization.rs:1770-...)
# ---------------------------------------------------------------------------


def _verify_closure(record: _Record, document: HclDocument, limits) -> MaterializationProvenanceMap:
    entries: list[MaterializationProvenanceEntry] = []
    units = 0

    def push_origin(input_location: MaterializationInputLocation, origin: MaterializedOrigin) -> None:
        nonlocal units
        units += 1
        if units > limits.max_provenance_entries:
            raise HclMaterializationFailure(
                HclMaterializationFailureKind.RESOURCE_LIMIT,
                resource_name="provenance-entries",
            )
        entries.append(
            MaterializationProvenanceEntry(input=input_location, outputs=(origin,))
        )

    def origin(node: NodeRef, span: Span) -> MaterializedOrigin:
        return MaterializedOrigin(
            snapshot=document.snapshot_identity(),
            node=node,
            span=span,
            relation=MaterializationRelation.DIRECT,
        )

    def root_path() -> ValuePath:
        return ValuePath.root()

    push_origin(
        MaterializationInputLocation.value(root_path()),
        origin(
            document.authority.node_ref(0, _document_role()),
            document.authority.span(0, len(document.source.bytes())),
        ),
    )

    def walk_body(record_body: _Body, native_body, body_path: ValuePath) -> None:
        if len(record_body.items) != len(native_body.items):
            raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
        for index, (record_item, native_item) in enumerate(zip(record_body.items, native_body.items)):
            item_path = body_path.child(
                ValuePathSegment(ValuePathSegmentKind.SEQUENCE_ELEMENT, index)
            )
            if record_item.kind == "attribute":
                attribute = native_item.as_attribute()
                if attribute is None or attribute.name != record_item.name:
                    raise HclMaterializationFailure(
                        HclMaterializationFailureKind.FORMATION_FAILED
                    )
                push_origin(
                    MaterializationInputLocation.value(item_path),
                    origin(
                        document.node_ref(attribute),
                        document.authority.span(
                            attribute.name_span.start_byte,
                            attribute.expression.span.end_byte,
                        ),
                    ),
                )
                value_path = item_path.child(
                    ValuePathSegment(ValuePathSegmentKind.OBJECT_VALUE, "value")
                )
                _verify_value(record_item.value, attribute.expression, value_path, document)
                push_origin(
                    MaterializationInputLocation.value(value_path),
                    origin(
                        document.node_ref(attribute.expression),
                        attribute.expression.span,
                    ),
                )
            else:
                block = native_item.as_block()
                if (
                    block is None
                    or block.block_type != record_item.block_type
                    or tuple(label.text for label in block.labels) != record_item.labels
                ):
                    raise HclMaterializationFailure(
                        HclMaterializationFailureKind.FORMATION_FAILED
                    )
                push_origin(
                    MaterializationInputLocation.value(item_path),
                    origin(document.node_ref(block), block.span),
                )
                for label in block.labels:
                    push_origin(
                        MaterializationInputLocation.value(item_path),
                        origin(document.node_ref(label), label.span),
                    )
                body_path_nested = item_path.child(
                    ValuePathSegment(ValuePathSegmentKind.OBJECT_VALUE, "body")
                )
                walk_body(record_item.body, block.body, body_path_nested)

    def _verify_value(
        promised: _ValueNode,
        native: HclExpression,
        path: ValuePath,
        document: HclDocument,
    ) -> None:
        kind = promised.kind
        if kind in ("integer", "real"):
            if native.kind.name is not HclExpressionKindName.NUMBER:
                raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
            if native.kind.payload.canonical_decimal != promised.text:
                raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
            if kind == "integer" and "." in promised.text:
                raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
            if kind == "real" and "." not in promised.text:
                raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
        elif kind == "string":
            if not is_literal_complete(native):
                raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
            literal = literal_value(native)
            if literal.kind != "string" or literal.text != promised.text:
                raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
        elif kind == "boolean":
            if native.kind.name is not HclExpressionKindName.BOOLEAN or native.kind.payload != promised.flag:
                raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
        elif kind == "null":
            if native.kind.name is not HclExpressionKindName.NULL:
                raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
        elif kind == "tuple":
            if native.kind.name is not HclExpressionKindName.TUPLE:
                raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
            elements = native.kind.payload
            if len(elements) != len(promised.elements):
                raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
            for index, (promised_element, native_element) in enumerate(zip(promised.elements, elements)):
                child_path = path.child(
                    ValuePathSegment(ValuePathSegmentKind.SEQUENCE_ELEMENT, index)
                )
                _verify_value(promised_element, native_element, child_path, document)
        elif kind == "object":
            if native.kind.name is not HclExpressionKindName.OBJECT:
                raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
            entries = native.kind.payload
            if len(entries) != len(promised.entries):
                raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
            for index, ((promised_key, promised_value), native_entry) in enumerate(
                zip(promised.entries, entries)
            ):
                actual_key = _native_key_text(native_entry.key)
                if actual_key != promised_key:
                    raise HclMaterializationFailure(
                        HclMaterializationFailureKind.FORMATION_FAILED
                    )
                child_path = path.child(
                    ValuePathSegment(ValuePathSegmentKind.ENTRY_VALUE, index)
                )
                _verify_value(promised_value, native_entry.value, child_path, document)
        else:  # expression
            if native != promised.expression:
                raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
            if structural_fingerprint(native) != structural_fingerprint(promised.expression):
                raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)

    walk_body(record.body, document.body, root_path())
    return MaterializationProvenanceMap.new(entries, document.snapshot_identity(), limits)


def _native_key_text(key) -> str:
    """The canonical string spelling of one native object key, exactly as
    the canonical emitter renders it (materialization.rs:1255-1264)."""
    if key.kind == "identifier":
        return key.name or ""
    if key.kind == "number" and key.number is not None:
        return key.number.canonical_decimal
    if key.kind == "template" and key.template is not None:
        text = ""
        for part in key.template.parts:
            if part.kind != "literal":
                raise HclMaterializationFailure(
                    HclMaterializationFailureKind.FORMATION_FAILED
                )
            text += part.text
        return text
    if key.kind == "paren" and key.inner is not None:
        if not is_literal_complete(key.inner):
            raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
        literal = literal_value(key.inner)
        if literal.kind in ("integer", "real", "string"):
            return literal.text
        if literal.kind == "boolean":
            return "true" if literal.flag else "false"
        if literal.kind == "null":
            return "null"
        raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)
    raise HclMaterializationFailure(HclMaterializationFailureKind.FORMATION_FAILED)


def _document_role():
    from consema.document.structural import NodeRole

    return NodeRole.HCL_DOCUMENT
