"""Canonical `xml.safe-canonical-document@1` materialization (RFC 0012 §10).

Authority:

- RFC 0012 §10 (docs/rfcs/0012-xml-1.0-safe-profile-v1.md:350-372): the
  canonical style consumes one fully validated ``xml.element-tree@1`` value
  and creates a new ``xml.1.0-safe@1`` Document; it is not W3C Canonical
  XML and does not claim C14N equivalence; the style deterministically
  chooses declaration spelling, quote style, indentation, namespace
  declaration placement, empty-element spelling, reference spelling, and
  LF/CRLF according to the request; UTF-8/UTF-16LE/UTF-16BE output are
  supported under the source rules; UTF-16 output always carries its BOM;
  materialization validates the complete tree before allocating proportional
  output, encodes it, reparses the exact generated bytes under the promised
  Profile and encoding, and compares the reparsed native tree to the
  promised input semantics; failure returns no target Document or partial
  output.
- The writer, encoding, closure verification, and failure mapping transcribe
  crates/consema-xml/src/materialization.rs:34-1366 (request validation
  90-107; parse limits 109-140; encode_text 143-172; Record validation
  238-500; PrefixTable 502-526; Writer 565-900; verify_closure 912-1210) —
  byte/registry arbitration only.
- The completion algebra reuses consema.document.materialization
  (CompleteMaterialization/FailedMaterializationAttempt/fidelity/report/
  provenance), whose failure-to-code mapping is frozen there
  (error_registry.rs:556-604).
- Vector coverage: conformance/vectors/xml-1-0-safe-v1.json cases
  ``xml.materialization.canonical-round-trip`` (lines 352-388),
  ``xml.materialization.escapes-content`` (390-417),
  ``xml.materialization.invalid-record-rejected`` (419-435).

go/xml is a cross-reference only; no code structure is copied.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field

from consema.core.value import PortableValue
from consema.document.limits import ParseLimits
from consema.document.materialization import (
    CompleteMaterialization,
    FailedMaterializationAttempt,
    MaterializationFailure,
    MaterializationFailureKind,
    MaterializationFidelity,
    MaterializationInputLocation,
    MaterializationLimits,
    MaterializationProvenanceEntry,
    MaterializationProvenanceMap,
    MaterializationRelation,
    MaterializationReport,
    MaterializationRequest,
    MaterializationResult,
    MaterializedOrigin,
    NewlinePolicy,
)
from consema.document.source import SourceEncoding, SourceEncodingKind
from consema.document.structural import FormationStatus, NodeRef, NodeRole, Span

from consema.xml.document import Document, XmlElement, text_semantic
from consema.xml.namespaces import XML_NAMESPACE_URI
from consema.xml.parser import XmlEncodingSelection, XmlParseLimits, XmlProfile, parse
from consema.xml.paths import (
    AssociationLocation,
    AssociationRole,
    ValuePath,
    ValuePathSegment,
)


def materialize(value: PortableValue, request: MaterializationRequest) -> MaterializationResult:
    """Materializes one ``xml.element-tree@1`` record into a new canonical
    ``xml.1.0-safe@1`` document (materialization.rs:36-50)."""
    try:
        complete = _materialize_complete(value, request)
        return complete
    except MaterializationFailure as failure:
        return FailedMaterializationAttempt(
            failure=failure,
            report=MaterializationReport(),
            analyzed_input_paths=(),
        )


def _materialize_complete(
    value: PortableValue, request: MaterializationRequest
) -> CompleteMaterialization:
    _validate_request(request)
    input_record = _Record.validate(value)
    writer = _Writer(request.limits)
    writer.emit_document(input_record, request)
    text = writer.output
    bytes_output = _encode_text(text, request.encoding, request.limits.max_output_bytes)
    document = parse(
        bytes_output,
        XmlProfile.SAFE_V1,
        XmlEncodingSelection.profile_default(),
        _parse_limits(request.limits),
    )
    if document.status is not FormationStatus.COMPLETE:
        raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
    provenance = _verify_closure(input_record, document, writer.items, request.limits)
    return CompleteMaterialization(
        document=document,
        fidelity=MaterializationFidelity.EXACT,
        report=MaterializationReport(),
        provenance=provenance,
    )


def _validate_request(request: MaterializationRequest) -> None:
    """materialization.rs:90-107."""
    if (request.target_profile.id, request.target_profile.version) != ("xml.1.0-safe", 1):
        raise MaterializationFailure(MaterializationFailureKind.UNSUPPORTED_PROFILE)
    if (request.style.id, request.style.version) != ("xml.safe-canonical-document", 1):
        raise MaterializationFailure(MaterializationFailureKind.UNSUPPORTED_STYLE)
    if request.encoding.kind not in (
        SourceEncodingKind.UTF8,
        SourceEncodingKind.UTF16LE,
        SourceEncodingKind.UTF16BE,
    ):
        raise MaterializationFailure(MaterializationFailureKind.UNSUPPORTED_ENCODING)
    if request.newline not in (NewlinePolicy.LF, NewlinePolicy.CRLF):
        raise MaterializationFailure(MaterializationFailureKind.UNSUPPORTED_NEWLINE)


def _parse_limits(limits: MaterializationLimits) -> XmlParseLimits:
    """materialization.rs:109-140: parse limits derived from the
    materialization limits."""
    return XmlParseLimits(
        common=ParseLimits(
            max_source_bytes=limits.max_output_bytes,
            max_nesting_depth=limits.max_depth,
            max_token_count=limits.max_output_bytes,
            max_node_count=limits.max_input_nodes,
            max_diagnostics=limits.max_report_entries,
        ),
        max_decoded_utf8_bytes=limits.max_output_bytes * 3,
        max_decoded_scalars=limits.max_output_bytes,
        max_element_count=limits.max_input_nodes,
        max_attribute_count=limits.max_input_nodes,
        max_namespace_declaration_count=limits.max_input_nodes,
        max_mixed_content_items=limits.max_input_nodes,
        max_qname_length=limits.max_output_bytes,
        max_namespace_uri_length=limits.max_output_bytes,
        max_attribute_value_length=limits.max_output_bytes,
        max_comment_length=limits.max_output_bytes,
        max_pi_length=limits.max_output_bytes,
        max_cdata_length=limits.max_output_bytes,
        max_text_length=limits.max_output_bytes,
        max_dtd_bytes=limits.max_output_bytes,
        max_entity_declarations=limits.max_input_nodes,
        max_entity_references=limits.max_input_nodes,
        max_entity_expansion_depth=limits.max_depth,
        max_expanded_entity_bytes=limits.max_output_bytes,
        max_expanded_entity_scalars=limits.max_output_bytes,
        max_entity_amplification_ratio=2**63 - 1,
        max_recovery_regions=limits.max_report_entries,
    )


def _encode_text(text: bytes, encoding: SourceEncoding, max_output_bytes: int) -> bytes:
    """Encodes canonical UTF-8 text into the requested output encoding
    (materialization.rs:143-172)."""
    if encoding.kind is SourceEncodingKind.UTF8:
        output = text
    elif encoding.kind in (SourceEncodingKind.UTF16LE, SourceEncodingKind.UTF16BE):
        decoded = text.decode("utf-8")
        if encoding.kind is SourceEncodingKind.UTF16LE:
            prefix = b"\xff\xfe"
            units = decoded.encode("utf-16-le")
        else:
            prefix = b"\xfe\xff"
            units = decoded.encode("utf-16-be")
        output = prefix + units
    else:
        raise MaterializationFailure(MaterializationFailureKind.UNSUPPORTED_ENCODING)
    if len(output) > max_output_bytes:
        raise MaterializationFailure(
            MaterializationFailureKind.RESOURCE_LIMIT, name="output-bytes"
        )
    return output


# ---------------------------------------------------------------------------
# Validated input record mirroring xml.element-tree@1 (materialization.rs:
# 174-500)
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class _DeclarationRecord:
    version: str
    encoding: str | None
    standalone: bool | None
    path: ValuePath


@dataclass(frozen=True, slots=True)
class _EntityRecord:
    name: str
    replacement: str
    path: ValuePath


@dataclass(frozen=True, slots=True)
class _AttributeRecord:
    namespace: str | None
    local: str
    value: str
    path: ValuePath


class _FragmentKind(enum.Enum):
    LITERAL = "literal"
    CHARACTER_REFERENCE = "character-reference"
    PREDEFINED_ENTITY = "predefined-entity"
    GENERAL_ENTITY = "general-entity"


@dataclass(frozen=True, slots=True)
class _FragmentRecord:
    kind: _FragmentKind
    text: str | None = None
    name: str | None = None
    resolved: str | None = None


class _ContentKind(enum.Enum):
    ELEMENT = "element"
    TEXT = "text"
    CDATA = "cdata"
    COMMENT = "comment"
    PROCESSING_INSTRUCTION = "processing-instruction"


@dataclass(frozen=True, slots=True)
class _ContentRecord:
    kind: _ContentKind
    element: "_ElementRecord | None" = None
    fragments: tuple[_FragmentRecord, ...] = ()
    text: str | None = None
    target: str | None = None
    content: str | None = None
    path: ValuePath = field(default_factory=ValuePath.root)


@dataclass(frozen=True, slots=True)
class _ElementRecord:
    namespace: str | None
    local: str
    namespaces: tuple[tuple[str | None, str], ...]
    attributes: tuple[_AttributeRecord, ...]
    content: tuple[_ContentRecord, ...]
    path: ValuePath


@dataclass(frozen=True, slots=True)
class _Record:
    declaration: _DeclarationRecord | None
    entities: tuple[_EntityRecord, ...]
    root: _ElementRecord

    @classmethod
    def validate(cls, value: PortableValue) -> _Record:
        """Validates one complete ``xml.element-tree@1`` value
        (materialization.rs:238-304)."""
        record = _expect_string_field(value, "record", ValuePath.root())
        if record != "xml.element-tree@1":
            raise MaterializationFailure(
                MaterializationFailureKind.INVALID_REQUEST,
                detail="input record is not xml.element-tree@1",
            )
        root_path = ValuePath.root().child(ValuePathSegment.object_value("root"))
        root_value = _expect_object_field(value, "root", root_path)
        declaration = None
        declaration_path = ValuePath.root().child(ValuePathSegment.object_value("declaration"))
        declaration_value = _optional_object_field(value, "declaration")
        if declaration_value is not None:
            version = _expect_string_field(declaration_value, "version", declaration_path)
            if version != "1.0":
                raise MaterializationFailure(
                    MaterializationFailureKind.UNREPRESENTABLE,
                    name="declaration-version",
                )
            declaration = _DeclarationRecord(
                version=version,
                encoding=_optional_string_field(declaration_value, "encoding", declaration_path),
                standalone=_optional_boolean_field(declaration_value, "standalone", declaration_path),
                path=declaration_path,
            )
        entities: list[_EntityRecord] = []
        entities_path = ValuePath.root().child(ValuePathSegment.object_value("entities"))
        entities_value = _optional_sequence_field(value, "entities")
        if entities_value is not None:
            for index, entity in enumerate(entities_value):
                entity_path = entities_path.child(ValuePathSegment.sequence_element(index))
                name = _expect_string_field(entity, "name", entity_path)
                replacement = _expect_string_field(entity, "replacement", entity_path)
                if "<" in replacement:
                    raise MaterializationFailure(
                        MaterializationFailureKind.UNREPRESENTABLE,
                        name="entity-replacement",
                    )
                entities.append(_EntityRecord(name=name, replacement=replacement, path=entity_path))
        root = _ElementRecord.validate(root_value, root_path)
        return _Record(declaration=declaration, entities=tuple(entities), root=root)


def _ElementRecord_validate(value: PortableValue, path: ValuePath) -> _ElementRecord:
    """Recursive element-record validation (materialization.rs:306-500)."""
    namespace, local = _expect_expanded_name(value, path)
    namespaces: list[tuple[str | None, str]] = []
    bindings_path = path.child(ValuePathSegment.object_value("namespaces"))
    bindings_value = _optional_sequence_field(value, "namespaces")
    if bindings_value is not None:
        for index, binding in enumerate(bindings_value):
            binding_path = bindings_path.child(ValuePathSegment.sequence_element(index))
            prefix = _optional_string_field(binding, "prefix", binding_path)
            uri = _expect_string_field(binding, "uri", binding_path)
            namespaces.append((prefix, uri))
    attributes: list[_AttributeRecord] = []
    attributes_path = path.child(ValuePathSegment.object_value("attributes"))
    attributes_value = _optional_sequence_field(value, "attributes")
    if attributes_value is not None:
        for index, attribute in enumerate(attributes_value):
            attribute_path = attributes_path.child(ValuePathSegment.sequence_element(index))
            attr_namespace, attr_local = _expect_expanded_name(attribute, attribute_path)
            value_text = _expect_string_field(attribute, "value", attribute_path)
            attributes.append(
                _AttributeRecord(
                    namespace=attr_namespace, local=attr_local, value=value_text, path=attribute_path
                )
            )
    content: list[_ContentRecord] = []
    content_path = path.child(ValuePathSegment.object_value("content"))
    content_value = _optional_sequence_field(value, "content")
    if content_value is not None:
        for index, item in enumerate(content_value):
            item_path = content_path.child(ValuePathSegment.sequence_element(index))
            if item.kind.value == "Object" and _has_object_field(item, "expanded-name"):
                content.append(
                    _ContentRecord(
                        kind=_ContentKind.ELEMENT,
                        element=_ElementRecord_validate(item, item_path),
                        path=item_path,
                    )
                )
                continue
            kind = _expect_string_field(item, "kind", item_path)
            if kind == "text":
                fragments_path = item_path.child(ValuePathSegment.object_value("fragments"))
                fragments_value = _expect_object_field(item, "fragments", fragments_path)
                fragment_list: list[_FragmentRecord] = []
                if fragments_value.kind.value != "Sequence":
                    raise MaterializationFailure(
                        MaterializationFailureKind.UNREPRESENTABLE,
                        name="text-fragments",
                    )
                for fragment_index, fragment in enumerate(fragments_value.as_sequence()):
                    fragment_path = fragments_path.child(
                        ValuePathSegment.sequence_element(fragment_index)
                    )
                    fragment_kind = _expect_string_field(fragment, "kind", fragment_path)
                    if fragment_kind == "literal":
                        fragment_list.append(
                            _FragmentRecord(
                                kind=_FragmentKind.LITERAL,
                                text=_expect_string_field(fragment, "text", fragment_path),
                            )
                        )
                    elif fragment_kind == "character-reference":
                        resolved = _expect_string_field(fragment, "resolved", fragment_path)
                        if len(resolved) != 1:
                            raise MaterializationFailure(
                                MaterializationFailureKind.UNREPRESENTABLE,
                                name="character-reference",
                            )
                        fragment_list.append(
                            _FragmentRecord(
                                kind=_FragmentKind.CHARACTER_REFERENCE, resolved=resolved
                            )
                        )
                    elif fragment_kind in ("predefined-entity", "general-entity"):
                        fragment_list.append(
                            _FragmentRecord(
                                kind=_FragmentKind.PREDEFINED_ENTITY
                                if fragment_kind == "predefined-entity"
                                else _FragmentKind.GENERAL_ENTITY,
                                name=_expect_string_field(fragment, "name", fragment_path),
                                resolved=_expect_string_field(fragment, "resolved", fragment_path),
                            )
                        )
                    else:
                        raise MaterializationFailure(
                            MaterializationFailureKind.UNREPRESENTABLE,
                            name="fragment-kind",
                        )
                content.append(
                    _ContentRecord(
                        kind=_ContentKind.TEXT,
                        fragments=tuple(fragment_list),
                        path=item_path,
                    )
                )
            elif kind == "cdata":
                content.append(
                    _ContentRecord(
                        kind=_ContentKind.CDATA,
                        text=_expect_string_field(item, "text", item_path),
                        path=item_path,
                    )
                )
            elif kind == "comment":
                content.append(
                    _ContentRecord(
                        kind=_ContentKind.COMMENT,
                        text=_expect_string_field(item, "text", item_path),
                        path=item_path,
                    )
                )
            elif kind == "processing-instruction":
                content.append(
                    _ContentRecord(
                        kind=_ContentKind.PROCESSING_INSTRUCTION,
                        target=_expect_string_field(item, "target", item_path),
                        content=_optional_string_field(item, "content", item_path),
                        path=item_path,
                    )
                )
            else:
                raise MaterializationFailure(
                    MaterializationFailureKind.UNREPRESENTABLE, name="content-kind"
                )
    names: list[tuple[str | None, str]] = []
    for attribute in attributes:
        if (attribute.namespace, attribute.local) in names:
            raise MaterializationFailure(
                MaterializationFailureKind.INVALID_REQUEST,
                detail="duplicate expanded attribute in input record",
            )
        names.append((attribute.namespace, attribute.local))
    return _ElementRecord(
        namespace=namespace,
        local=local,
        namespaces=tuple(namespaces),
        attributes=tuple(attributes),
        content=tuple(content),
        path=path,
    )


_ElementRecord.validate = staticmethod(_ElementRecord_validate)


# ---------------------------------------------------------------------------
# Field accessors (materialization.rs:1228-1366)
# ---------------------------------------------------------------------------


def _object_field(value: PortableValue, name: str) -> PortableValue | None:
    if value.kind.value != "Object":
        return None
    for key, entry in value.as_object():
        if key == name:
            return entry
    return None


def _has_object_field(value: PortableValue, name: str) -> bool:
    return _object_field(value, name) is not None


def _expect_object_field(value: PortableValue, name: str, path: ValuePath) -> PortableValue:
    field_value = _object_field(value, name)
    if field_value is None:
        raise MaterializationFailure(
            MaterializationFailureKind.INVALID_REQUEST, detail="missing record field"
        )
    return field_value


def _optional_object_field(value: PortableValue, name: str) -> PortableValue | None:
    return _object_field(value, name)


def _expect_string_field(value: PortableValue, name: str, path: ValuePath) -> str:
    field_value = _expect_object_field(value, name, path)
    if field_value.kind.value != "String":
        raise MaterializationFailure(
            MaterializationFailureKind.UNREPRESENTABLE, name="string-field"
        )
    return field_value.as_string()


def _optional_string_field(value: PortableValue, name: str, path: ValuePath) -> str | None:
    field_value = _object_field(value, name)
    if field_value is None or field_value.kind.value == "Null":
        return None
    if field_value.kind.value != "String":
        raise MaterializationFailure(
            MaterializationFailureKind.UNREPRESENTABLE, name="string-field"
        )
    return field_value.as_string()


def _optional_boolean_field(value: PortableValue, name: str, path: ValuePath) -> bool | None:
    field_value = _object_field(value, name)
    if field_value is None or field_value.kind.value == "Null":
        return None
    if field_value.kind.value != "Boolean":
        raise MaterializationFailure(
            MaterializationFailureKind.UNREPRESENTABLE, name="boolean-field"
        )
    return field_value.as_boolean()


def _optional_sequence_field(value: PortableValue, name: str):
    field_value = _object_field(value, name)
    if field_value is None:
        return None
    if field_value.kind.value != "Sequence":
        raise MaterializationFailure(
            MaterializationFailureKind.UNREPRESENTABLE, name="sequence-field"
        )
    return field_value.as_sequence()


def _expect_expanded_name(value: PortableValue, path: ValuePath) -> tuple[str | None, str]:
    """Reads an expanded-name object (materialization.rs:1356-1366)."""
    name_path = path.child(ValuePathSegment.object_value("expanded-name"))
    name = _expect_object_field(value, "expanded-name", name_path)
    namespace = _optional_string_field(name, "namespace", name_path)
    local = _expect_string_field(name, "local", name_path)
    return namespace, local


# ---------------------------------------------------------------------------
# Canonical writer (materialization.rs:502-900)
# ---------------------------------------------------------------------------


class _PrefixTable:
    """Deterministic generated-prefix assignment by first-encounter order
    (materialization.rs:502-526)."""

    __slots__ = ("entries", "next")

    def __init__(self) -> None:
        self.entries: dict[str, str] = {}
        self.next = 0

    def prefix_for(self, namespace: str, default: str | None) -> str:
        if namespace == default:
            return ""
        if namespace == XML_NAMESPACE_URI:
            return "xml"
        prefix = self.entries.get(namespace)
        if prefix is not None:
            return prefix
        self.next += 1
        prefix = f"ns{self.next}"
        self.entries[namespace] = prefix
        return prefix


class _InputItemKind(enum.Enum):
    DECLARATION = "declaration"
    ENTITY = "entity"
    ELEMENT = "element"
    NAMESPACE_BINDING = "namespace-binding"
    ATTRIBUTE = "attribute"
    TEXT = "text"
    FRAGMENT = "fragment"
    CDATA = "cdata"
    COMMENT = "comment"
    PROCESSING_INSTRUCTION = "processing-instruction"


@dataclass(frozen=True, slots=True)
class _InputItem:
    """One input location recorded during generation (materialization.rs:
    528-563)."""

    kind: _InputItemKind
    path: ValuePath

    def location(self) -> MaterializationInputLocation:
        if self.kind is _InputItemKind.NAMESPACE_BINDING:
            return MaterializationInputLocation.association(
                AssociationLocation(
                    path=self.path, ordinal=0, role=AssociationRole.OBJECT_ENTRY
                )
            )
        return MaterializationInputLocation.value(self.path)


class _Writer:
    __slots__ = ("limits", "input_nodes", "output", "prefixes", "scope", "items")

    def __init__(self, limits: MaterializationLimits) -> None:
        self.limits = limits
        self.input_nodes = 0
        self.output = bytearray()
        self.prefixes = _PrefixTable()
        self.scope: list[tuple[str | None, str]] = []
        self.items: list[_InputItem] = []

    def step(self) -> None:
        self.input_nodes += 1
        if self.input_nodes > self.limits.max_input_nodes:
            raise MaterializationFailure(
                MaterializationFailureKind.RESOURCE_LIMIT, name="input-nodes"
            )

    def push(self, data: bytes) -> None:
        self.output.extend(data)
        if len(self.output) > self.limits.max_output_bytes:
            raise MaterializationFailure(
                MaterializationFailureKind.RESOURCE_LIMIT, name="output-bytes"
            )

    def spelling_prefix(self, uri: str | None) -> str | None:
        """Spelling prefix for one expanded namespace (materialization.rs:
        601-621). ``None`` means the URI is not bound in scope and a
        declaration must be generated."""
        if uri is None:
            return ""
        if uri == XML_NAMESPACE_URI:
            return "xml"
        for prefix, bound in reversed(self.scope):
            if prefix is None and bound == uri:
                return ""
        for prefix, bound in reversed(self.scope):
            if prefix is not None and bound == uri:
                return prefix
        return None

    def push_escaped_text(self, text: str) -> None:
        """Materialization.rs:623-634: ``&`` and ``<`` are escaped."""
        for character in text:
            if character == "&":
                self.push(b"&amp;")
            elif character == "<":
                self.push(b"&lt;")
            else:
                self.push(character.encode("utf-8"))

    def push_escaped_attribute(self, text: str) -> None:
        """Materialization.rs:636-648: ``&``, ``<``, and ``"`` are escaped."""
        for character in text:
            if character == "&":
                self.push(b"&amp;")
            elif character == "<":
                self.push(b"&lt;")
            elif character == '"':
                self.push(b"&quot;")
            else:
                self.push(character.encode("utf-8"))

    def emit_document(self, input_record: _Record, request: MaterializationRequest) -> None:
        """materialization.rs:650-715."""
        self.step()
        if input_record.declaration is not None:
            declaration = input_record.declaration
            self.items.append(_InputItem(_InputItemKind.DECLARATION, declaration.path))
            self.push(b'<?xml version="')
            self.push_escaped_attribute(declaration.version)
            self.push(b'"')
            declared_encoding = declaration.encoding
            if declared_encoding is None and request.encoding.kind in (
                SourceEncodingKind.UTF16LE,
                SourceEncodingKind.UTF16BE,
            ):
                declared_encoding = "UTF-16"
            if declared_encoding is not None:
                self.push(b' encoding="')
                self.push_escaped_attribute(declared_encoding)
                self.push(b'"')
            if declaration.standalone is not None:
                self.push(b' standalone="yes"' if declaration.standalone else b' standalone="no"')
            self.push(b"?>")
        if input_record.entities:
            self.push(b"<!DOCTYPE ")
            root_prefix = self.spelling_prefix(input_record.root.namespace)
            if root_prefix is None:
                raise MaterializationFailure(
                    MaterializationFailureKind.UNREPRESENTABLE, name="doctype-name"
                )
            doctype_name = (
                input_record.root.local
                if root_prefix == ""
                else f"{root_prefix}:{input_record.root.local}"
            )
            self.push(doctype_name.encode("utf-8"))
            self.push(b" [")
            for entity in input_record.entities:
                self.items.append(_InputItem(_InputItemKind.ENTITY, entity.path))
                self.push(b"<!ENTITY ")
                self.push(entity.name.encode("utf-8"))
                self.push(b' "')
                self.push_escaped_attribute(entity.replacement)
                self.push(b'">')
            self.push(b"]>")
        self.emit_element(input_record.root, 0)
        self.push(request.newline.bytes)

    def emit_element(self, element: _ElementRecord, depth: int) -> None:
        """materialization.rs:717-899."""
        self.step()
        if depth > self.limits.max_depth:
            raise MaterializationFailure(
                MaterializationFailureKind.RESOURCE_LIMIT, name="input-depth"
            )
        self.items.append(_InputItem(_InputItemKind.ELEMENT, element.path))
        scope_len = len(self.scope)
        for prefix, uri in element.namespaces:
            self.scope.append((prefix, uri))
        element_prefix = self.spelling_prefix(element.namespace)
        if element_prefix is None:
            # Unbound URI in a hand-built record: declare a generated
            # default namespace on this element.
            uri = element.namespace or XML_NAMESPACE_URI
            if uri == XML_NAMESPACE_URI:
                element_prefix = "xml"
            else:
                self.push(b"<")
                self.push(element.local.encode("utf-8"))
                self.push(b' xmlns="')
                self.push_escaped_attribute(uri)
                self.push(b'"')
                self.scope.append((None, uri))
                self.items.append(_InputItem(_InputItemKind.NAMESPACE_BINDING, element.path))
                element_prefix = ""
        self.push(b"<")
        if element_prefix == "":
            self.push(element.local.encode("utf-8"))
        else:
            self.push(element_prefix.encode("utf-8"))
            self.push(b":")
            self.push(element.local.encode("utf-8"))
        for prefix, uri in element.namespaces:
            self.items.append(_InputItem(_InputItemKind.NAMESPACE_BINDING, element.path))
            if prefix is not None:
                self.push(b" xmlns:")
                self.push(prefix.encode("utf-8"))
                self.push(b'="')
                self.push_escaped_attribute(uri)
                self.push(b'"')
            else:
                self.push(b' xmlns="')
                self.push_escaped_attribute(uri)
                self.push(b'"')
        for attribute in element.attributes:
            self.items.append(_InputItem(_InputItemKind.ATTRIBUTE, attribute.path))
            attribute_prefix = self.spelling_prefix(attribute.namespace)
            if attribute_prefix is None:
                uri = attribute.namespace or XML_NAMESPACE_URI
                generated = self.prefixes.prefix_for(uri, None)
                self.push(b" xmlns:")
                self.push(generated.encode("utf-8"))
                self.push(b'="')
                self.push_escaped_attribute(uri)
                self.push(b'"')
                self.scope.append((generated, uri))
                self.items.append(_InputItem(_InputItemKind.NAMESPACE_BINDING, attribute.path))
                attribute_prefix = generated
            self.push(b" ")
            if attribute_prefix == "":
                self.push(attribute.local.encode("utf-8"))
            else:
                self.push(attribute_prefix.encode("utf-8"))
                self.push(b":")
                self.push(attribute.local.encode("utf-8"))
            self.push(b'="')
            self.push_escaped_attribute(attribute.value)
            self.push(b'"')
        if not element.content:
            self.push(b"/>")
            del self.scope[scope_len:]
            return
        self.push(b">")
        for item in element.content:
            if item.kind is _ContentKind.ELEMENT:
                assert item.element is not None
                self.emit_element(item.element, depth + 1)
            elif item.kind is _ContentKind.TEXT:
                self.items.append(_InputItem(_InputItemKind.TEXT, item.path))
                for fragment in item.fragments:
                    self.items.append(_InputItem(_InputItemKind.FRAGMENT, item.path))
                    if fragment.kind is _FragmentKind.LITERAL:
                        self.push_escaped_text(fragment.text or "")
                    elif fragment.kind is _FragmentKind.CHARACTER_REFERENCE:
                        self.push(f"&#{ord(fragment.resolved)};".encode("utf-8"))
                    else:
                        self.push(b"&")
                        self.push((fragment.name or "").encode("utf-8"))
                        self.push(b";")
            elif item.kind is _ContentKind.CDATA:
                self.items.append(_InputItem(_InputItemKind.CDATA, item.path))
                if "]]>" in (item.text or ""):
                    raise MaterializationFailure(
                        MaterializationFailureKind.UNREPRESENTABLE, name="cdata-text"
                    )
                self.push(b"<![CDATA[")
                self.push((item.text or "").encode("utf-8"))
                self.push(b"]]>")
            elif item.kind is _ContentKind.COMMENT:
                self.items.append(_InputItem(_InputItemKind.COMMENT, item.path))
                if "--" in (item.text or "") or (item.text or "").endswith("-"):
                    raise MaterializationFailure(
                        MaterializationFailureKind.UNREPRESENTABLE, name="comment-text"
                    )
                self.push(b"<!--")
                self.push((item.text or "").encode("utf-8"))
                self.push(b"-->")
            else:
                self.items.append(
                    _InputItem(_InputItemKind.PROCESSING_INSTRUCTION, item.path)
                )
                if (item.target or "").lower() == "xml" or "?>" in (item.content or ""):
                    raise MaterializationFailure(
                        MaterializationFailureKind.UNREPRESENTABLE, name="processing-instruction"
                    )
                self.push(b"<?")
                self.push((item.target or "").encode("utf-8"))
                if item.content is not None:
                    self.push(b" ")
                    self.push(item.content.encode("utf-8"))
                self.push(b"?>")
        self.push(b"</")
        if element_prefix == "":
            self.push(element.local.encode("utf-8"))
        else:
            self.push(element_prefix.encode("utf-8"))
            self.push(b":")
            self.push(element.local.encode("utf-8"))
        self.push(b">")
        del self.scope[scope_len:]


# ---------------------------------------------------------------------------
# Closure verification and provenance (materialization.rs:902-1210)
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class _OutputItem:
    node: NodeRef
    span: Span
    relation: MaterializationRelation


def _verify_closure(
    input_record: _Record,
    document: Document,
    items: list[_InputItem],
    limits: MaterializationLimits,
) -> MaterializationProvenanceMap:
    """Walks the input record and the reparsed document in lockstep and
    pairs every recorded input location with its exact output origin
    (materialization.rs:912-1014)."""
    outputs: list[_OutputItem] = []
    root = document.root()
    if root is None:
        raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
    # Declaration closure.
    if input_record.declaration is not None:
        reparsed_declaration = document.declaration()
        if reparsed_declaration is None:
            raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
        if (
            reparsed_declaration.version != input_record.declaration.version
            or (reparsed_declaration.standalone[1] if reparsed_declaration.standalone else None)
            != input_record.declaration.standalone
        ):
            raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
    elif document.declaration() is not None:
        raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
    # Entity closure.
    reparsed_doctype = document.doctype()
    if reparsed_doctype is not None:
        reparsed_entities = reparsed_doctype.entities
        if len(reparsed_entities) != len(input_record.entities) or any(
            reparsed.name != declared.name or reparsed.replacement != declared.replacement
            for reparsed, declared in zip(reparsed_entities, input_record.entities)
        ):
            raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
    elif input_record.entities:
        raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
    if input_record.declaration is not None:
        outputs.append(
            _OutputItem(
                node=document.node_ref(1, NodeRole.XML_DECLARATION),
                span=document.declaration().span,
                relation=MaterializationRelation.DIRECT,
            )
        )
    if reparsed_doctype is not None:
        for entity in reparsed_doctype.entities:
            outputs.append(
                _OutputItem(
                    node=document.node_ref(2, NodeRole.XML_DOCTYPE),
                    span=entity.span,
                    relation=MaterializationRelation.DIRECT,
                )
            )
    context = _ClosureContext(document, outputs, limits)
    context.element(input_record.root, root)
    if len(outputs) != len(items):
        raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
    entries: list[MaterializationProvenanceEntry] = []
    for item, output in zip(items, outputs):
        location = item.location()
        origin = MaterializedOrigin(
            snapshot=document.snapshot_identity(),
            node=output.node,
            span=output.span,
            relation=output.relation,
        )
        if entries and entries[-1].input == location:
            last = entries[-1]
            entries[-1] = MaterializationProvenanceEntry(
                input=last.input, outputs=last.outputs + (origin,)
            )
            continue
        entries.append(
            MaterializationProvenanceEntry(input=location, outputs=(origin,))
        )
    return MaterializationProvenanceMap.new(entries, document.snapshot_identity(), limits)


class _ClosureContext:
    __slots__ = ("document", "outputs", "limits")

    def __init__(self, document: Document, outputs: list[_OutputItem], limits) -> None:
        self.document = document
        self.outputs = outputs
        self.limits = limits

    def push(self, node: NodeRef, span: Span, relation: MaterializationRelation) -> None:
        if len(self.outputs) >= self.limits.max_provenance_entries:
            raise MaterializationFailure(
                MaterializationFailureKind.RESOURCE_LIMIT, name="provenance-entries"
            )
        self.outputs.append(_OutputItem(node=node, span=span, relation=relation))

    def element(self, input_element: _ElementRecord, element) -> None:
        """One element closure walk (materialization.rs:1040-1209)."""
        self.push(element.node_ref(), element.span(), MaterializationRelation.DIRECT)
        expanded = element.expanded()
        if expanded is None:
            raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
        name_matches = (
            input_element.namespace is not None
            and expanded.namespace is not None
            and input_element.namespace == expanded.namespace
        ) or (input_element.namespace is None and expanded.namespace is None)
        if not name_matches or expanded.local != input_element.local:
            raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
        for binding in element.namespace_bindings():
            self.push(
                self.document.node_ref(binding.ordinal, NodeRole.XML_NAMESPACE_BINDING),
                binding.span,
                MaterializationRelation.GENERATED,
            )
        attributes = element.attributes()
        if len(attributes) != len(input_element.attributes):
            raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
        for input_attribute, attribute in zip(input_element.attributes, attributes):
            self.push(
                self.document.node_ref(attribute.ordinal, NodeRole.XML_ATTRIBUTE),
                attribute.span,
                MaterializationRelation.DIRECT,
            )
            if attribute.expanded is None:
                raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
            attr_name_matches = (
                input_attribute.namespace is not None
                and attribute.expanded.namespace is not None
                and input_attribute.namespace == attribute.expanded.namespace
            ) or (input_attribute.namespace is None and attribute.expanded.namespace is None)
            if (
                not attr_name_matches
                or attribute.expanded.local != input_attribute.local
                or attribute.normalized_value != input_attribute.value
            ):
                raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
        children = element.children()
        if len(children) != len(input_element.content):
            raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
        for child, input_item in zip(children, input_element.content):
            child_element = (
                XmlElement(self.document, child.data.index)
                if child.kind.value == "element"
                else None
            )
            if child_element is not None and input_item.kind is _ContentKind.ELEMENT:
                assert input_item.element is not None
                self.element(input_item.element, child_element)
            elif input_item.kind is _ContentKind.TEXT:
                if child.kind.value != "text":
                    raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
                text = child.data
                self.push(
                    self.document.node_ref(text.ordinal, NodeRole.XML_TEXT),
                    text.span,
                    MaterializationRelation.DIRECT,
                )
                semantic: list[str] = []
                for fragment in input_item.fragments:
                    if fragment.kind is _FragmentKind.LITERAL:
                        semantic.append(_normalize_line_ends(fragment.text or ""))
                    elif fragment.kind is _FragmentKind.CHARACTER_REFERENCE:
                        semantic.append(fragment.resolved or "")
                    else:
                        semantic.append(_normalize_line_ends(fragment.resolved or ""))
                    first_span = (
                        text.fragments[0].span if text.fragments else text.span
                    )
                    self.push(
                        self.document.node_ref(text.ordinal, NodeRole.XML_ENTITY_REFERENCE),
                        first_span,
                        MaterializationRelation.DIRECT,
                    )
                if text_semantic(text) != "".join(semantic):
                    raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
            elif input_item.kind is _ContentKind.CDATA:
                if child.kind.value != "cdata":
                    raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
                cdata = child.data
                self.push(
                    self.document.node_ref(cdata.ordinal, NodeRole.XML_CDATA),
                    cdata.span,
                    MaterializationRelation.DIRECT,
                )
                if cdata.text != input_item.text:
                    raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
            elif input_item.kind is _ContentKind.COMMENT:
                if child.kind.value != "comment":
                    raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
                comment = child.data
                self.push(
                    self.document.node_ref(comment.ordinal, NodeRole.XML_COMMENT),
                    comment.span,
                    MaterializationRelation.DIRECT,
                )
                if comment.text != input_item.text:
                    raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
            elif input_item.kind is _ContentKind.PROCESSING_INSTRUCTION:
                if child.kind.value != "processing-instruction":
                    raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
                pi = child.data
                self.push(
                    self.document.node_ref(pi.ordinal, NodeRole.XML_PROCESSING_INSTRUCTION),
                    pi.span,
                    MaterializationRelation.DIRECT,
                )
                if pi.target != input_item.target or (
                    pi.content[1] if pi.content is not None else None
                ) != input_item.content:
                    raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)
            else:
                raise MaterializationFailure(MaterializationFailureKind.FORMATION_FAILED)


def _normalize_line_ends(text: str) -> str:
    """XML 1.0 line-end normalization for one fragment (materialization.rs:
    1212-1226)."""
    output: list[str] = []
    index = 0
    while index < len(text):
        character = text[index]
        if character == "\r":
            output.append("\n")
            if index + 1 < len(text) and text[index + 1] == "\n":
                index += 1
        else:
            output.append(character)
        index += 1
    return "".join(output)
